### ISSUE TITLE
java.lang.NoSuchMethodError: com.github.benmanes.caffeine.cache.Policy$VarExpiration.put(Ljava/lang/Object;Ljava/lang/Object;JLjava/util/concurrent/TimeUnit;)Ljava/lang/Object;

### ISSUE THREAD

**Issue by xhaimxd** [ben-manes/caffeine#1011]
I used below method and it shows no such method error:
```
cache.policy().expireVariably().ifPresent(p -> {
     p.put(x, xx, Duration.ofSeconds(10000))
}}
```

i found that it happed because i code it in my own sdk use version 3.1.6, but it was downgrade to 2.8.8 by spring management.
however, i checked the code in 2.8.8, it really had the method:
```
default void put(@NonNull K key, @NonNull V value, @NonNull Duration duration) {
      // This method will be abstract in version 3.0.0
      put(key, value, duration.toNanos(), TimeUnit.NANOSECONDS);
    }
```

most stack info like below:
```
java.lang.NoSuchMethodError: com.github.benmanes.caffeine.cache.Policy$VarExpiration.put(Ljava/lang/Object;Ljava/lang/Object;Ljava/time/Duration;)Ljava/lang/Object;
	<my own methods>
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2344)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1908)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2342)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2325)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108)
	at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
	<my own methods>
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.xnzk.im.message.ImMessageSender.sendMessageCardByPhone(ImMessageSender.java:65)
	at com.xnzk.im.message.ImMessageSender.sendMessageCardByPhone(ImMessageSender.java:55)
	at com.xndb.bpmn.adapter.eventhandler.rabbitmq.CompleteTaskErrorHandler.sendToIm(CompleteTaskErrorHandler.java:77)
	at com.xndb.bpmn.adapter.eventhandler.rabbitmq.CompleteTaskErrorHandler.handleError(CompleteTaskErrorHandler.java:55)
	at org.springframework.amqp.rabbit.listener.adapter.MessagingMessageListenerAdapter.invokeHandlerAndProcessResult(MessagingMessageListenerAdapter.java:162)
	at org.springframework.amqp.rabbit.listener.adapter.MessagingMessageListenerAdapter.onMessage(MessagingMessageListenerAdapter.java:133)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:1591)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.actualInvokeListener(AbstractMessageListenerContainer.java:1510)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:1498)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:1489)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:1433)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:970)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:916)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$1600(SimpleMessageListenerContainer.java:83)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.mainLoop(SimpleMessageListenerContainer.java:1291)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1197)
	at java.base/java.lang.Thread.run(Thread.java:835)
```

is there some fault i used?

update: I found the error method is : java.lang.Object com.github.benmanes.caffeine.cache.Policy$VarExpiration.put(java.lang.Object, java.lang.Object, long, java.util.concurrent.TimeUnit)
but in the code, this method is void return type, i thought it was why this error appear, so why?

**Comment by ben-manes** [comment]
Java's method resolution has strict signature binary compatibility that is looser than at compile time. This was a source compatible change but, as you noted, not a binary compatible one because the return type changed. These type of minor api improvements required meant waiting for a major version, where it was not typically used in common framework code. If you force Spring to upgrade, then I think it should work fine since the apis that it uses are binary compatible.

While this was expected, many years ago I made that mistake not realizing how binary resolution worked. CLHM's `maximumWeight` had its `int` promoted to a `long`, but I did not provide an overloaded method as I assumed it would be dynamically resolved when linking. I only found out when seeing some groovy code (maybe grails?) that did some ugly reflection to workaround it. I believe that widening types was later supported in Java 8, but in Java 5 that was an incompatibility.

If you read discussions on JEP 394 vs Kotlin's flow-sensitive typing, you'll see this topic asked about in regards to why a new variable is needed. The answer is wrt overloading rules where `method(Object o)` differs from `method(String s)`, where the comiler's understanding at the call-site dictates which one is called rather than the runtime type.

[JLS-15.12](https://docs.oracle.com/javase/specs/jls/se8/html/jls-15.html#jls-15.12) might give you more details as to why and what the rules are.

**Comment by xhaimxd** [comment]
that's true, the reason was in my sdk, the caffine version was 3.1.6, this put method has return type 'V', and when it was downgrade to 2.8.x, this method had void return type. so that idea could not found the mistake cuz the method was existed though the return type was wrong, i just downgrade my sdk version. thanks for your help
