### ISSUE TITLE
@DataJpaTest with JCache/Caffeine causes InvalidStateException in JUnit 5

### ISSUE THREAD

**Issue by amoffet** [ben-manes/caffeine#1021]
I am using Caffeine and JCache 2.9.3 with Spring Boot.  The use case is simple - I've enable 2nd Level caching with Hibernate and have an entity that I've set up a cache for.  It works great.  But when running a @DataJpaTest on another repository (Different entity), I get the exception found at the end of this message.  This occurs because @Transactional is part of the composition of @DataJpaTest and TransactionalTestExecutionListener therefore attempts to roll back the transaction.  This results in JCache trying to put() on a cache that is closed (or non-existent in my case).  

Thanks for the awesome work on Caffeine and JCache.

<#8a542f56> java.lang.IllegalStateException: null
at com.github.benmanes.caffeine.jcache.CacheProxy.requireNotClosed(CacheProxy.java:1085)
at com.github.benmanes.caffeine.jcache.CacheProxy.put(CacheProxy.java:306)
at org.hibernate.cache.jcache.internal.JCacheAccessImpl.putIntoCache(JCacheAccessImpl.java:43)
at org.hibernate.cache.spi.support.DirectAccessRegionTemplate.putIntoCache(DirectAccessRegionTemplate.java:44)
at org.hibernate.cache.internal.TimestampsCacheEnabledImpl.invalidate(TimestampsCacheEnabledImpl.java:95)
at org.hibernate.engine.spi.ActionQueue$AfterTransactionCompletionProcessQueue.afterTransactionCompletion(ActionQueue.java:995)
at org.hibernate.engine.spi.ActionQueue.afterTransactionCompletion(ActionQueue.java:513)
at org.hibernate.internal.SessionImpl.afterTransactionCompletion(SessionImpl.java:2462)
at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.afterTransactionCompletion(JdbcCoordinatorImpl.java:456)
at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.afterCompletionCallback(JdbcResourceLocalTransactionCoordinatorImpl.java:203)
at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.access$400(JdbcResourceLocalTransactionCoordinatorImpl.java:40)
at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.rollback(JdbcResourceLocalTransactionCoordinatorImpl.java:305)
at org.hibernate.engine.transaction.internal.TransactionImpl.rollback(TransactionImpl.java:142)
at org.springframework.orm.jpa.JpaTransactionManager.doRollback(JpaTransactionManager.java:589)\n\t... 2 frames excluded
at org.springframework.test.context.transaction.TransactionContext.endTransaction(TransactionContext.java:128)
at org.springframework.test.context.transaction.TransactionalTestExecutionListener.afterTestMethod(TransactionalTestExecutionListener.java:255)
at org.springframework.test.context.TestContextManager.afterTestMethod(TestContextManager.java:445)
at org.springframework.test.context.junit.jupiter.SpringExtension.afterEach(SpringExtension.java:206)
at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAfterEachCallbacks$12(TestMethodTestDescriptor.java:257)
at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAllAfterMethodsOrCallbacks$13(TestMethodTestDescriptor.java:273)
at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAllAfterMethodsOrCallbacks$14(TestMethodTestDescriptor.java:273)
at java.util.ArrayList.forEach(ArrayList.java:1511)
at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAllAfterMethodsOrCallbacks(TestMethodTestDescriptor.java:272)
at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAfterEachCallbacks(TestMethodTestDescriptor.java:256)
at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:141)
at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)\n\t... 43 frames truncated\n"

**Comment by ben-manes** [comment]
Unfortunately I am not sure what we can do here, because the JCache specification and TCK requires checking if closed: `IllegalStateException if the cache is {@link #isClosed()}`. Since JCache also requires its resolution to be a static singleton, it makes testing more frustrating as the shared state leaks across independent tests. I think the best that you can do is close the CacheManager after a test case to remove it from the `CachingProvider` mappings, or if that's too broad use `destroyCache` to target individual instances. Then the next usage should reload it anew.

I'm not sure how helpful that answer is, but I don't know if I there is anything better that JCache allows.

**Comment by amoffet** [comment]
I didn't think it would be easy.  Thanks for your suggestions!
