### ISSUE TITLE
Using JBoss ScheduledExecutorService leads to IllegalStateException in Scheduler

### ISSUE THREAD

**Issue by clone1612** [ben-manes/caffeine#1449]
We're using Caffeine for an application deployed on a JBoss application server. In order to make sure all threads are correctly managed we use the default JBoss (Scheduled)ExecutorService:

```
    @Resource(mappedName = "java:jboss/ee/concurrency/executor/default")
    private ExecutorService cacheMaintenanceExecutor;
    @Resource(mappedName = "java:jboss/ee/concurrency/scheduler/default")
    private ScheduledExecutorService cacheMaintenanceScheduler;
```

Cache configuration looks like this:
```
        return Caffeine.newBuilder()
                // Let cache only use threads managed by JBoss
                .scheduler(Scheduler.forScheduledExecutorService(cacheMaintenanceScheduler))
                .executor(cacheMaintenanceExecutor)
                // Limit cache size by configuring a lifetime for each entry
                .expireAfterAccess(Duration.ofSeconds(expirationInSeconds))
                // Protect against OutOfMemory by configuring a maximum amount of cache entries
                .maximumSize(maxSize)
                // Add logger in order to detect an inappropriate limit on the amount of cache entries
                .evictionListener((RemovalListener<TransformFormFormatRequestType, String>) (key, value, cause) -> {
                    if (cause == RemovalCause.SIZE) {
                        LOGGER.warn("Transformation cache entry was evicted as cache was full");
                    }
                })
                .build();
```

However when entries start to expire they're not removed, as task scheduling failed with the following exception:
```
Exception thrown by scheduler; discarded task: java.lang.IllegalStateException: Lifecycle operation not supported
    at org.glassfish.javax.enterprise.concurrent@1.1.1.redhat-00001//org.glassfish.enterprise.concurrent.AbstractManagedExecutorServiceAdapter.isShutdown(AbstractManagedExecutorServiceAdapter.java:45)
    at deployment.*-war.war//com.github.benmanes.caffeine.cache.ExecutorServiceScheduler.schedule(Scheduler.java:116)
    at deployment.*-war.war//com.github.benmanes.caffeine.cache.GuardedScheduler.schedule(Scheduler.java:144)
    at deployment.*-war.war//com.github.benmanes.caffeine.cache.Pacer.schedule(Pacer.java:63)
    at deployment.*-war.war//com.github.benmanes.caffeine.cache.BoundedLocalCache.expireEntries(BoundedLocalCache.java:913)
    at deployment.*-war.war//com.github.benmanes.caffeine.cache.BoundedLocalCache.maintenance(BoundedLocalCache.java:1721)
    at deployment.*-war.war//com.github.benmanes.caffeine.cache.BoundedLocalCache.performCleanUp(BoundedLocalCache.java:1660)
    at deployment.*-war.war//com.github.benmanes.caffeine.cache.BoundedLocalCache$PerformCleanupTask.run(BoundedLocalCache.java:3886)
    at org.jboss.as.ee@7.4.13.GA-redhat-00002//org.jboss.as.ee.concurrent.ControlPointUtils$ControlledRunnable.run(ControlPointUtils.java:125)
    at org.wildfly.security.elytron-private@1.15.20.Final-redhat-00001//org.wildfly.security.auth.server.SecurityIdentity.runAsConsumer(SecurityIdentity.java:376)
    at org.wildfly.security.elytron-private@1.15.20.Final-redhat-00001//org.wildfly.security.auth.server.Scoped.runAsConsumer(Scoped.java:112)
    at org.wildfly.security.elytron-private@1.15.20.Final-redhat-00001//org.wildfly.security.auth.server.Scoped.runAs(Scoped.java:60)
    at org.jboss.as.ee@7.4.13.GA-redhat-00002//org.jboss.as.ee.concurrent.SecurityIdentityUtils.lambda$doIdentityWrap$1(SecurityIdentityUtils.java:63)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at org.glassfish.javax.enterprise.concurrent@1.1.1.redhat-00001//org.glassfish.enterprise.concurrent.internal.ManagedFutureTask.run(ManagedFutureTask.java:117)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base/java.lang.Thread.run(Thread.java:840)
    at org.glassfish.javax.enterprise.concurrent@1.1.1.redhat-00001//org.glassfish.enterprise.concurrent.ManagedThreadFactoryImpl$ManagedThread.run(ManagedThreadFactoryImpl.java:227)
```

These executor services are managed by JBoss, and looking at https://developer.jboss.org/thread/239373 lifecycle methods aren't allowed to be called. 

In the `Scheduler` class I can see the culprit at line 116:
```
    if (scheduledExecutorService.isShutdown()) {
      return DisabledFuture.INSTANCE;
    }
```

Is this intended behavior? Or is there a more appropriate way of using Caffeine caches with managed executor services?

Additional information:
* Java version: `java-17-openjdk-17.0.9.0.9-2.el8.x86_64`
* JBoss version: `JBoss EAP 7.4.13.GA (WildFly Core 15.0.30.Final-redhat-00001)`

**Comment by ben-manes** [comment]
I’m not familiar with ManagedExecutorService but disallowing query methods seems like an errorprone choice as not part of the interface contract. 

can you use ForwardingScheduledExecutorService from guava or a similar delegate to always return false?

**Comment by clone1612** [comment]
Using a delegate is a possibility, although we're avoiding external dependencies. Implementing one shouldn't be a problem, although it isn't ideal.

Given the fact that the class doesn't fully respect the interface as you mentioned there don't seem to be many alternatives:
* Checking the provided executor service doesn't implement the J2EE `ManagedExecutorService` interface? (external dependency, not desired)
* Providing a `Scheduler.forManagedScheduledExecutorService` which skips the isshutdown check?

**Comment by clone1612** [comment]
It's our policy to only use the managed executors, that way we're certain of what we're working with and the lifecycle is automatically managed.

I've implemented a workaround as discussed above, although it's not ideal. The fault doesn't lie with Caffeine, but I think updating the wiki to mention the (possible) issue with a managed service could be useful in case anyone else encounters the same? But seeing I'm the first to report it the chance seems low.

**Comment by ben-manes** [comment]
Since the scheduler is only a few lines then implementing your own without that check is probably simpler. I think that I added the check just to avoid spamming the logs on server shutdown when a race between an orderly shutdown and some work might trigger that rejection. I’m not sure if it is useful but seemed harmless at the time, wdyt?

**Comment by clone1612** [comment]
> Since the scheduler is only a few lines then implementing your own without that check is probably simpler. I think that I added the check just to avoid spamming the logs on server shutdown when a race between an orderly shutdown and some work might trigger that rejection. I’m not sure if it is useful but seemed harmless at the time, wdyt?

Indeed, without the check a simple one-liner is possible. I went for that solution, thanks for the information and suggestions!

**Comment by ben-manes** [comment]
do you think the check is necessary for the general case or egregious for everyone? I'm unsure what the right next steps are and see three obvious options.
1. Close with maybe a doc update as a one-liner for users
2. Remove the check to rely on rejection, logging the exception, and users can suppress any spaminess in their logs
3. Wrap the `isShutdown` in a try-catch, cache the result in a flag, and set the flag if on exceptional call

**Comment by clone1612** [comment]
Style wise I’m not a fan of the third option, feels a bit strange. Option 2 would work, inside the schedule call (execute call on executor) there is already a similar principle being used.

A `ManagedExecutorServiceScheduler` class which doesn’t perform the check could be a 4th option. Gives some flexibility to tweak behaviour if any other managed platform issues would ever appear. But as I seem to be the first one experiencing this issue it’s understandable that option 1 would be picked.

**Comment by ben-manes** [comment]
Thanks @clone1612! I went with adding a javadoc hint.
