### ISSUE TITLE
Exceptions when "closing" a cache

### ISSUE THREAD

**Issue by spand** [ben-manes/caffeine#1476]
Right off the bat: We get a lot of exceptions (see below) in our "integration/e2e" test logs because we shutdown the executors used by caffeine.

It is not a correctness problem per se but I would prefer not to have "yeah ignore those" exceptions in our test logs. I know its something of my own doing by shutting down the executors from out under it.. but at the time assumed it was fine as long as no further requests were made to it. Something that appears to be correct with the exception of the maintenance work.

So the question is: Is it possible to gracefully shutting down a cache instance? or am I doing it wrong ?

```
WARNING: Exception thrown when submitting maintenance task
java.util.concurrent.RejectedExecutionException: Task com.github.benmanes.caffeine.cache.BoundedLocalCache$PerformCleanupTask@39da005b rejected from java.util.concurrent.ThreadPoolExecutor@3de5833f[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 1409]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2065)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:833)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1365)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.scheduleDrainBuffers(BoundedLocalCache.java:1575)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.scheduleAfterWrite(BoundedLocalCache.java:1542)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.afterWrite(BoundedLocalCache.java:1477)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.remap(BoundedLocalCache.java:2801)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.compute(BoundedLocalCache.java:2662)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$refreshIfNeeded$5(BoundedLocalCache.java:1325)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
```

**Comment by ben-manes** [comment]
The cache doesn’t have a shutdown lifecycle, so yeah it’s for you to decide. You could pass a custom executor that uses caller runs instead of aborts on shutdown. wdyt?
