### ISSUE TITLE
ClassCastException on expiry

### ISSUE THREAD

**Issue by ennishol** [ben-manes/caffeine#1497]
Hi,
when using cache.get(key, function) a warning is logged 
````
WARN: Exception thrown by eviction listener
java.lang.ClassCastException: class java.lang.String cannot be cast to class com.github.benmanes.caffeine.jcache.Expirable (java.lang.String is in module java.base of loader 'bootstrap'; com.github.benmanes.caffeine.jcache.Expirable is in unnamed module of loader 'app')
	at com.github.benmanes.caffeine.jcache.event.JCacheEvictionListener.onRemoval(JCacheEvictionListener.java:35)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.notifyEviction(BoundedLocalCache.java:432)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2703)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1940)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2675)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2658)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:112)
	at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
````
Is this a bug or is my configuration wrong?
Thank you in advance!

Reproducer:
```
        <dependency>
            <groupId>javax.cache</groupId>
            <artifactId>cache-api</artifactId>
            <version>1.1.1</version>
        </dependency>
        <dependency>
            <groupId>com.github.ben-manes.caffeine</groupId>
            <artifactId>caffeine</artifactId>
            <version>3.1.5</version>
        </dependency>
        <dependency>
            <groupId>com.github.ben-manes.caffeine</groupId>
            <artifactId>jcache</artifactId>
            <version>3.1.5</version>
        </dependency>
```

```
package com.example;

import com.github.benmanes.caffeine.jcache.configuration.CaffeineConfiguration;
import com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider;

import javax.cache.Cache;
import javax.cache.CacheManager;
import javax.cache.Caching;
import java.time.Duration;
import java.util.OptionalLong;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.logging.ConsoleHandler;
import java.util.logging.Level;
import java.util.logging.Logger;

import static java.lang.System.Logger.Level.INFO;

@SuppressWarnings("unchecked")
public class CaffeineJCacheExample {
    static final System.Logger logger = System.getLogger(CaffeineJCacheExample.class.getName());


    public static void main(String[] args) throws InterruptedException {
        setupLogger();
        AtomicInteger count = new AtomicInteger();
        CacheManager cacheManager = getCacheManager();
        Cache<Object, Object> cache = createCache(cacheManager, "c1");
        logger.log(INFO, "First get with function {0}",
                cache.unwrap(com.github.benmanes.caffeine.cache.Cache.class).get("key", k -> "value " + count.getAndIncrement()));
        logger.log(INFO, "Second get with function {0}",
                cache.unwrap(com.github.benmanes.caffeine.cache.Cache.class).get("key", k -> "value " + count.getAndIncrement()));
        Thread.sleep(200L); // Wait longer than the expiry duration
        logger.log(INFO, "After expiry get with function {0}",
                cache.unwrap(com.github.benmanes.caffeine.cache.Cache.class).get("key", k -> "value " + count.getAndIncrement()));

        logger.log(INFO, "===================== now using get,put without function param");
        cache.put("foo", "new value");
        logger.log(INFO, "first get {0}", cache.get("foo"));
        logger.log(INFO, "second get  {0}", cache.get("foo"));
        Thread.sleep(200L); // Wait longer than the expiry duration
        logger.log(INFO, "After expiry get {0}", cache.get("foo"));

    }

    private static CacheManager getCacheManager() {
        var caffeine = CaffeineCachingProvider.class.getCanonicalName();
        return Caching.getCachingProvider(caffeine).getCacheManager();
    }

    private static <K, V> Cache<K, V> createCache(CacheManager cacheManager, String name) {
        CaffeineConfiguration<K, V> config1 = new CaffeineConfiguration<>();
        config1.setMaximumSize(OptionalLong.of(2L));
        config1.setExpireAfterWrite(OptionalLong.of(Duration.ofMillis(50).toNanos()));
        config1.setStoreByValue(false);
        config1.setStatisticsEnabled(true);
        return cacheManager.createCache(name, config1);
    }

    private static void setupLogger() {
        ConsoleHandler consoleHandler = new ConsoleHandler();
        consoleHandler.setLevel(Level.ALL);
        Logger caffeineLogger = Logger.getLogger("com.github.benmanes.caffeine");
        caffeineLogger.setLevel(Level.ALL);
        caffeineLogger.addHandler(consoleHandler);

        Logger appLogger = Logger.getLogger(CaffeineJCacheExample.class.getCanonicalName());
        appLogger.setLevel(Level.ALL);
        appLogger.addHandler(consoleHandler);
    }
}

```

**Comment by ben-manes** [comment]
I guess it is because your `getCacheManager` is specifying a ClassLoader and that is somehow conflicting with other loaded classes, so it’s not castable? Why not use the default ClassLoader?

**Comment by ben-manes** [comment]
Oh! It’s because you unwrap and modify the raw cache to insert new data. The raw cache uses a value wrapper and so you corrupt the state. You’re supposed to use the jsr apis and not have vendor classes in your code.

**Comment by ennishol** [comment]
@ben-manes  I'm unwrapping it to use atomic write with function param. there is no API for it in jcache. It would be nice to be able to provide a custom JCacheEvictionListener to avoid this, wdyt?

**Comment by ben-manes** [comment]
JCache has the invoke api which is atomic in Caffeine. Otherwise you would use their CacheLoader instead.

**Comment by ennishol** [comment]
Thanks, I'll do that
