### ISSUE TITLE
Issue with hanging lookups when migrating guava cache to caffeine

### ISSUE THREAD

**Issue by pjfanning** [ben-manes/caffeine#209]
I have a test project at https://github.com/pjfanning/nested-cache
The Guava version works but the Caffeine version hangs.
I'm saying that this is a good way to use Loading caches but my team has some existing Guava caches and I guess we got away with writing a few caches that have this kind of nested behaviour.

This was tested with (but I found in an Oracle JDK8 and other Zulu 8 JDKs too):
openjdk version "1.8.0_144"
OpenJDK Runtime Environment (Zulu 8.23.0.3-macosx) (build 1.8.0_144-b01)
OpenJDK 64-Bit Server VM (Zulu 8.23.0.3-macosx) (build 25.144-b01, mixed mode)

```
"main" #1 prio=5 os_prio=31 tid=0x00007ffc2c801800 nid=0x1703 runnable [0x0000700000217000]
   java.lang.Thread.State: RUNNABLE
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1934)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2032)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2015)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:113)
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:65)
	at nested.CaffeineNestedCache$FactorialLoader.load(CaffeineNestedCache.java:17)
	at nested.CaffeineNestedCache$FactorialLoader.load(CaffeineNestedCache.java:11)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalLoadingCache.lambda$new$0(BoundedLocalCache.java:3352)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalLoadingCache$$Lambda$3/1848415041.apply(Unknown Source)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2034)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$$Lambda$4/1825027294.apply(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853)
	- locked <0x000000076c9a5ca0> (a java.util.concurrent.ConcurrentHashMap$ReservationNode)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2032)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2015)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:113)
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:65)
	at nested.CaffeineNestedCache.factorial(CaffeineNestedCache.java:27)
	at nested.CaffeineNestedCacheTest.testFactorial(CaffeineNestedCacheTest.java:10)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by ben-manes** [comment]
A recursive computation is not supported in Java’s maps. ConcurrentHashMap live locks and HashMap corrupts itself. In Java 9 both throw exceptions in those cases and the JavaDoc was updated.

Guava will throw an exception if the same key is recursed to. It’s not an intended feature to allow it otherwise, but hard to detect.

A solution is to use the synchronous view of an AsyncLoadingCache. The mappings will be established immediately with a future value and the computation scheduled. Then it will only deadlock if there is a circular dependency in the future chain.

**Comment by pjfanning** [comment]
Thanks Ben. We can try using the AsyncLoadingCache as you suggest.

**Comment by ben-manes** [comment]
Note that in your example, you can use `AsyncLoadingCache#synchronous()` to get a `LoadingCache` view. So hopefully the impact on your code is pretty minimal if you decide to use that trick.

**Comment by slovdahl** [comment]
I recently discovered that using an `AsyncLoadingCache` in cases like this is no silver bullet. I have seen exceptions like this a few times now:
```
Mar 12, 2018 8:46:49 AM com.github.benmanes.caffeine.cache.LocalAsyncLoadingCache lambda$get$3
WARNING: Exception thrown during asynchronous load
java.util.concurrent.CompletionException: java.util.concurrent.RejectedExecutionException: Thread limit exceeded replacing blocked worker
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run$$$capture(CompletableFuture.java:1592)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.util.concurrent.RejectedExecutionException: Thread limit exceeded replacing blocked worker
	at java.util.concurrent.ForkJoinPool.tryCompensate(ForkJoinPool.java:2011)
	at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3310)
	at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1729)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at com.github.benmanes.caffeine.cache.LocalAsyncLoadingCache$LoadingCacheView.get(LocalAsyncLoadingCache.java:400)
```

I don't think there's anything caffeine can do to fix this (except maybe document the risk of it happening?). Further reading of why it's happening, in the "Compensation Threads" section: http://moi.vonos.net/java/forkjoin.

It's easy to reproduce with [a synthetic test](https://gist.github.com/slovdahl/e0eba7c42f36b30c79a5b9f604ada1a0). I'm not, however, able to reliable reproduce the issue with the original code. This far, it has happened when the JVM was starting and the cache was being filled. This suggests that there might be something else using the common `ForkJoinPool` at the same time, so I'm not blaming caffeine at all here. Using another `Executor` for the cache might be one way of working around this.

**Comment by ben-manes** [comment]
hmm.. yes. I guess you would have to use `Executors.newCachedThreadPool()` instead to safely generate new threads. The deeper the recursion goes, the worse it gets as each step requires a new thread. Unfortunately there isn't much we can do here to help the situation.
