### ISSUE TITLE
WriteBehindCacheWriter - High CPU usage

### ISSUE THREAD

**Issue by manishonline** [ben-manes/caffeine#247]
I am seeing high CPU usage when example code given WriteBehindCacheWriter is added as a cache writer.

RxComputationThreadPool-1 is always running and accounts for 85% of the total CPU time consumed by my application. Any way to get around this?

`"RxComputationThreadPool-1" #51 daemon prio=5 os_prio=0 tid=0x0000000021287800 nid=0x4974 runnable [0x000000002602e000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.System.identityHashCode(Native Method)
	at org.netbeans.lib.profiler.server.ThreadInfo.getThreadHashCode(ThreadInfo.java:337)
	at org.netbeans.lib.profiler.server.ThreadInfo.getThreadInfoOrNull(ThreadInfo.java:343)
	at org.netbeans.lib.profiler.server.ThreadInfo.getThreadInfo(ThreadInfo.java:254)
	at org.netbeans.lib.profiler.server.ThreadInfo.getThreadInfo(ThreadInfo.java:250)
	at org.netbeans.lib.profiler.server.ProfilerRuntimeCPUFullInstr.methodEntry(ProfilerRuntimeCPUFullInstr.java:118)
	at io.reactivex.internal.operators.observable.ObservableBufferTimed$BufferExactUnboundedObserver.accept(ObservableBufferTimed.java:213)
	at io.reactivex.internal.operators.observable.ObservableBufferTimed$BufferExactUnboundedObserver.accept(ObservableBufferTimed.java:81)
	at io.reactivex.internal.observers.QueueDrainObserver.fastPathEmit(QueueDrainObserver.java:70)
	at io.reactivex.internal.operators.observable.ObservableBufferTimed$BufferExactUnboundedObserver.run(ObservableBufferTimed.java:209)
	at io.reactivex.internal.schedulers.InstantPeriodicTask.call(InstantPeriodicTask.java:57)
	at io.reactivex.internal.schedulers.InstantPeriodicTask.call(InstantPeriodicTask.java:29)
	at java.util.concurrent.FutureTask.run(FutureTask.java:270)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Redefined)
	at java.lang.Thread.run(Thread.java:748)
`

![image](https://user-images.githubusercontent.com/8766490/40263298-86841c4a-5b53-11e8-91fb-03b45c4ac7d0.png)

**Comment by manishonline** [comment]
It was an issue on my end itself. I was setting buffer time wrongly.
