### ISSUE TITLE
java.lang.NoClassDefFoundError: com/github/benmanes/caffeine/cache/tracing/Tracer when used in OSGI container

### ISSUE THREAD

**Issue by alexander-riss** [ben-manes/caffeine#29]
the cache.tracing package is not exported and in this way not visible when creating e.g. a LocalCache:

java.lang.NoClassDefFoundError: com/github/benmanes/caffeine/cache/tracing/Tracer
	at com.github.benmanes.caffeine.cache.LocalCache.tracer(LocalCache.java:64)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.<init>(BoundedLocalCache.java:139)
	at com.github.benmanes.caffeine.cache.LocalCacheFactory$SS.<init>(LocalCacheFactory.java:12966)
	at com.github.benmanes.caffeine.cache.LocalCacheFactory$SSMS.<init>(LocalCacheFactory.java:23034)
	at com.github.benmanes.caffeine.cache.LocalCacheFactory$SSMSA.<init>(LocalCacheFactory.java:23079)
	at com.github.benmanes.caffeine.cache.LocalCacheFactory.newBoundedLocalCache(LocalCacheFactory.java:795)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalManualCache.<init>(BoundedLocalCache.java:1779)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalManualCache.<init>(BoundedLocalCache.java:1775)
	at com.github.benmanes.caffeine.cache.Caffeine.build(Caffeine.java:814)

**Comment by ben-manes** [comment]
Sorry that iI haven't used OSGi so it's not tested, but I thought the bundle instructions were correct. The tracing jar is built with, 

```gradle
bundle {
  instruction 'Export-Package', 'com.github.benmanes.caffeine.cache.tracing.*'
}
```

**Comment by alexander-riss** [comment]
ah ok i did not realise that there are transitive dependencies - i'll give it a try

**Comment by alexander-riss** [comment]
i added the tracing-api bundle but as it seems this does not help much, since the com.github.ben-manes.caffeine is not importing the tracing bundle.

So adding that import would probably fix the issue and document this runtime dependency all at once

**Comment by ben-manes** [comment]
That makes sense that I missed the `Import-Package`. If there's an easy way to run an OSGi container in a unit test to verify compatibility, I'd appreciate some pointers. The fix should be available in the snapshot repository when the CI passes (~25 minutes) if you'd like to verify.

The tracing package will probably be removed in v2 since we collected enough data to simulate policies and choose an optimal one to replace LRU.

**Comment by ben-manes** [comment]
I probably need an import statement for the guava jar too...

**Comment by ben-manes** [comment]
Release v2.0 which fixes the OSGi manifests. It also removes the tracing packages, which are no longer needed due to choosing a new eviction policy. Sorry this took so long to release.

**Comment by gvsharma** [comment]
having this same issue with spring container, any suggestions?

**Comment by ben-manes** [comment]
I guess you're referring to this [StackOverflow issue](https://stackoverflow.com/questions/57962520/caffeine-cache-cannot-be-cast-to-org-springframework-cache-cache)? I think you are supposed to use Spring's `CaffeineCacheManager`, but I am not very familiar with Spring these days.

**Comment by gvsharma** [comment]
Thank you for your reply, resolved the issue
