### ISSUE TITLE
maintenance() blocks on computeIfPresent()

### ISSUE THREAD

**Issue by panghy** [ben-manes/caffeine#328]
Noticed that we have a bunch of threads blocked on put() due to performCleanUp() like so:

```
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.3/Native Method)
	- parking to wait for  <0x00007ece892b6498> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(java.base@11.0.3/LockSupport.java:194)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(java.base@11.0.3/AbstractQueuedSynchronizer.java:885)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(java.base@11.0.3/AbstractQueuedSynchronizer.java:917)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@11.0.3/AbstractQueuedSynchronizer.java:1240)
	at java.util.concurrent.locks.ReentrantLock.lock(java.base@11.0.3/ReentrantLock.java:267)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.performCleanUp(BoundedLocalCache.java:1403)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.afterWrite(BoundedLocalCache.java:1324)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.put(BoundedLocalCache.java:2021)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.put(BoundedLocalCache.java:1910)
	at com.github.benmanes.caffeine.cache.LocalManualCache.put(LocalManualCache.java:64)
```

Which is blocked because the evictionLock is held by a thread that's blocked on computeIfPresent():

```
   java.lang.Thread.State: BLOCKED (on object monitor)
	at java.util.concurrent.ConcurrentHashMap.computeIfPresent(java.base@11.0.3/ConcurrentHashMap.java:1813)
	- waiting to lock <0x00007ed9c1d96ca0> (a java.util.concurrent.ConcurrentHashMap$Node)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.evictEntry(BoundedLocalCache.java:862)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.evictFromMain(BoundedLocalCache.java:705)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.evictEntries(BoundedLocalCache.java:609)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.maintenance(BoundedLocalCache.java:1437)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.performCleanUp(BoundedLocalCache.java:1405)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$PerformCleanupTask.run(BoundedLocalCache.java:3278)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.3/ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.3/ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(java.base@11.0.3/Thread.java:834)
```

Which is blocked by a get():
```
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalLoadingCache.lambda$new$0(BoundedLocalCache.java:3670)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalLoadingCache$$Lambda$184/0x00007ec8971c3858.apply(Unknown Source)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2337)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$$Lambda$185/0x00007ec8971c1040.apply(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap.compute(java.base@11.0.3/ConcurrentHashMap.java:1947)
	- locked <0x00007ed9c1d96ca0> (a java.util.concurrent.ConcurrentHashMap$Node)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2335)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2318)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:111)
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:66)
```

Before I go further, if we transform the get() into a CompletableFuture (async cache) that should not block right? This is a cache with an expireAfterAccess, refreshAfterWrite and a weight limit.

**Comment by ben-manes** [comment]
Yes, an async cache helps to shrink the lock holding time (as not calling your foreign code under the lock). Setting a higher initial capacity can also help by increasing the number of hashmap locks.

You might need a timeout is in your loading code if it’s never completing, e.g. if due to external resource not responding.

**Comment by panghy** [comment]
Yeah it seems like even with an async cache it could still block on put:

```
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.3/Native Method)
	- parking to wait for  <0x00007ebbbfc19e50> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(java.base@11.0.3/LockSupport.java:194)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(java.base@11.0.3/AbstractQueuedSynchronizer.java:885)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(java.base@11.0.3/AbstractQueuedSynchronizer.java:917)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@11.0.3/AbstractQueuedSynchronizer.java:1240)
	at java.util.concurrent.locks.ReentrantLock.lock(java.base@11.0.3/ReentrantLock.java:267)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.performCleanUp(BoundedLocalCache.java:1403)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.afterWrite(BoundedLocalCache.java:1324)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.put(BoundedLocalCache.java:2021)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.put(BoundedLocalCache.java:1910)
	at com.github.benmanes.caffeine.cache.LocalAsyncCache.put(LocalAsyncCache.java:108)

```

**Comment by ben-manes** [comment]
There is something causing the maintenance (cleanUp) work to be stuck and not make progress. Typically we perform the map operation, add a write event to a ring buffer, and schedule that policy work (maintenance) on the executor. This way not all writes are serialized against the policy lock (like a synchronized LinkedHashMap as an LRU). However, if the ring buffer is full then we degrade to have writers take out the policy lock and do the work directly. This adds lets the maintenance worker be prioritized, which improves overall throughput and avoids runaway effects.

Above you showed the maintenance work blocked on `computeIfPresent`, where it is trying to evict an entry but has to re-check its status (e.g. maybe no longer expired). Usually that means there is some expensive user work never completing, like waiting for a response that does not timeout. An async cache usually wouldn't hit that because the map write operation is just adding/removing the future, which is executed asynchronously (assuming `Caffeine.executor` is not a same-thread executor). Can you share details on your usage? You can email me code privately if preferred.

**Comment by panghy** [comment]
Yeah seems like our executor degrades at high load into CALLER_RUNS executor which might be the culprit here. The alternative for us is to just forget about the refresh (don't queue on the executor) and throw a RejectedExecutionException and just do the refresh in the next round (seems like Caffeine would just log a message in that case).

**Comment by ben-manes** [comment]
You could supply a different executor for the refresh by overriding `asyncReload` (in either cache loader types). I tried to handle oddities like where the executor throws an exception and or caller runs., but it is hard to know what can break or how safely that is currently handled. If there are clear improvements that you see for us to make in the cache, I'd gladly consider them.

**Comment by ben-manes** [comment]
Closing but please reopen if you think there is anything for us to address. At the moment I don’t think there is a specific issue to investigate but could be wrong.
