### ISSUE TITLE
Deadlock in Synchronous refresh

### ISSUE THREAD

**Issue by julnamoo** [ben-manes/caffeine#352]
Trying to use caffein's `LoadingCache` in an asynchronous server, sometimes the `cache().get()` eats all threads and it runs out all threads to process the requests. This issue may look like #69 which is fixed by 2.7.0 as mentioned.

I believe the symptom is similar to #69 , and it has a similar cause: trying to `concurrentHashMap.compute()` with the same key in more than two threads. The thread exhaustion occurs even though the server doesn't have much traffic. (I met this issue during the local test also)

The server uses rxJava internally in order to cover the external API call.

This thread worked on a request with an external API call. The server has to use the sync `LoadingCache` due to a requirement even though the external API invocation is returned asynchronously in rxjava Observable. The thread got the API response in a synchronous way by `blockingGet` which returned the result in the same thread. After receiving,  it tries to put the value into the `concurrentHashMap` with the lock `0x000000077b94c9f8` in `compute()`

```
"armeria-common-worker-nio-2-15" #122 daemon prio=5 os_prio=31 tid=0x00007fb9ceb96800 nid=0x12d03 waiting on condition [0x00007000160f3000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x000000077b94ce70> (a java.util.concurrent.CountDownLatch$Sync)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
        at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
        at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:85)
        at io.reactivex.Single.blockingGet(Single.java:2835)
         ...
        at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalLoadingCache.lambda$new$0(BoundedLocalCache.java:3670)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalLoadingCache$$Lambda$500/1606570508.apply(Unknown Source)
        at com.github.benmanes.caffeine.cache.LocalCache.lambda$statsAware$0(LocalCache.java:142)
        at com.github.benmanes.caffeine.cache.LocalCache$$Lambda$1922/343807941.apply(Unknown Source)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2337)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache$$Lambda$1925/16125669.apply(Unknown Source)
        at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853)
        - locked <0x000000077b94c9f8> (a java.util.concurrent.ConcurrentHashMap$ReservationNode)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2335)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2318)
        at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:111)
        at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:66)
```

The below thread tried to get the value but the cache calls `map.compute()` for `cache.get()`, it tried to get a lock of the `Node` simultaneously, and it couldn't come back.

```
"armeria-common-worker-nio-2-1" #39 daemon prio=5 os_prio=31 tid=0x00007fb9cad9e000 nid=0x6a03 waiting for monitor entry [0x000070001233c000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1868)
        - waiting to lock <0x000000077b94c9f8> (a java.util.concurrent.ConcurrentHashMap$ReservationNode)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2335)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2318)
        at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:111)
        at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:66)
```

**Comment by ben-manes** [comment]
It sounds like you are not using `refreshAfterWrite`?

> trying to concurrentHashMap.compute() with the same key in more than two threads. The thread exhaustion occurs even though the server doesn't have much traffic.

In your stacktrace, the computation is blocked on an `CountDownLatch` call. When does this complete? From the trace, it would make sense that the external call does not return (e.g. fails to timeout) and that any other caller waiting on that request blocks indefinitely.

> The server has to use the sync LoadingCache due to a requirement even though the external API invocation is returned asynchronously in rxjava Observable. 

Can you explain this requirement? Usually one can adapt to a `CompleteableFuture<V>` and use `AsyncLoadingCache` to avoid blocking and extra threads. You can use `synchronous` to have a `LoadingCache` view.

Can you provide a test case?

**Comment by julnamoo** [comment]
> `refreshAfterWrite`

Used it definitely. Attached the cache builder usage:
```
Caffeine
        .newBuilder()
        .refreshAfterWrite(Duration.ofSeconds(10L))
        .maximumSize(50)
        .recordStats()
        .build(key -> doLoading(key).blockingGet());
```

> In your stacktrace, the computation is blocked on an CountDownLatch call. When does this complete?

It is one of the points I'm digging that why the latch doesn't finish. It is still under the investigation,.

> Requirement

On top of that, the method using the cache needs to return the value directly out of the asynchronous context due to the legacy and in order to avoid the huge changes 😢 

> `AsyncLoadingCache` with `synchronous()` option and a test case

Thanks for your advice. Let me try the `LoadingCacheView` and share the test case to reproduce it.

**Comment by ben-manes** [comment]
I believe using the `AsyncLoadingCache` should help a lot. It will then store a future as the cache value and not block within the hash table. If the future fails (or returns null value) then it will be removed automatically, handle stats correctly, ect. The blocking will then be performed outside of the cache on the returned future, which might fail due to the latch. Since it is a future / observable, you have the option of adding timeouts to avoid blocking indefinitely.

Unrelated but also useful info:
For a small cache with a lot of blocking activity, you might want to set a high `initialCapacity`. This is because `ConcurrentHashMap` blocks per hash bin, and the number of bins grows with the map size. This means that two entries under the same bin share a lock which can have an impact if the cache is small, entries are not long-lived, and computations are long. A higher `initialCapacity` reduces the chance of collision on a shared lock.

**Comment by ben-manes** [comment]
Any progress in your investigation?
