### ISSUE TITLE
Confusing exception message when setting invalid cache parameters

### ISSUE THREAD

**Issue by sigram** [ben-manes/caffeine#390]
I hit this when accidentally trying to setMaximumSize to -1:

`java.lang.IllegalArgumentException: null
	at com.github.benmanes.caffeine.cache.Caffeine.requireArgument(Caffeine.java:183) ~[caffeine-2.8.0.jar:?]
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.setMaximumSize(BoundedLocalCache.java:582) ~[caffeine-2.8.0.jar:?]
`
I think adding a short message about invalid value would help clarify the issue.

**Comment by ben-manes** [comment]
Thanks for letting me know!
