### ISSUE TITLE
"java.lang.AssertionError: Illegal bounds" on Cassandra

### ISSUE THREAD

**Issue by yakirgb** [ben-manes/caffeine#397]
Not sure if it's Cassandra or Caffeine issue, getting many errors of:
```
ERROR [ReadStage-22] 2020-02-24 15:13:26,127 AbstractLocalAwareExecutorService.java:169 - Uncaught exception on thread Thread[ReadStage-22,5,main]
java.lang.AssertionError: Illegal bounds [-1818017168..-1818017160); size: 2761628520
	at org.apache.cassandra.io.util.Memory.checkBounds(Memory.java:345) ~[apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.io.util.Memory.getLong(Memory.java:254) ~[apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.io.compress.CompressionMetadata.chunkFor(CompressionMetadata.java:234) ~[apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.io.util.CompressedChunkReader$Standard.readChunk(CompressedChunkReader.java:114) ~[apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.cache.ChunkCache.load(ChunkCache.java:158) ~[apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.cache.ChunkCache.load(ChunkCache.java:39) ~[apache-cassandra-3.11.6.jar:3.11.6]
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalLoadingCache.lambda$new$0(BoundedLocalCache.java:2949) ~[caffeine-2.2.6.jar:na]
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$15(BoundedLocalCache.java:1807) ~[caffeine-2.2.6.jar:na]
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1892) ~[na:1.8.0-zing_19.12.102.0]
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:1805) ~[caffeine-2.2.6.jar:na]
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:1788) ~[caffeine-2.2.6.jar:na]
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:97) ~[caffeine-2.2.6.jar:na]
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:66) ~[caffeine-2.2.6.jar:na]
	at org.apache.cassandra.cache.ChunkCache$CachingRebufferer.rebuffer(ChunkCache.java:236) ~[apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.cache.ChunkCache$CachingRebufferer.rebuffer(ChunkCache.java:214) ~[apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.io.util.RandomAccessReader.reBufferAt(RandomAccessReader.java:65) ~[apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.io.util.RandomAccessReader.seek(RandomAccessReader.java:207) ~[apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.io.util.FileHandle.createReader(FileHandle.java:150) ~[apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.io.sstable.format.SSTableReader.getFileDataInput(SSTableReader.java:1807) ~[apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.db.columniterator.AbstractSSTableIterator.<init>(AbstractSSTableIterator.java:103) ~[apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.db.columniterator.SSTableIterator.<init>(SSTableIterator.java:49) ~[apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.io.sstable.format.big.BigTableReader.iterator(BigTableReader.java:72) ~[apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.io.sstable.format.big.BigTableReader.iterator(BigTableReader.java:65) ~[apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.db.StorageHook$1.makeRowIterator(StorageHook.java:100) ~[apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.db.SinglePartitionReadCommand.queryMemtableAndSSTablesInTimestampOrder(SinglePartitionReadCommand.java:982) ~[apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.db.SinglePartitionReadCommand.queryMemtableAndDiskInternal(SinglePartitionReadCommand.java:693) ~[apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.db.SinglePartitionReadCommand.queryMemtableAndDisk(SinglePartitionReadCommand.java:670) ~[apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.db.SinglePartitionReadCommand.queryStorage(SinglePartitionReadCommand.java:504) ~[apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.db.ReadCommand.executeLocally(ReadCommand.java:423) ~[apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.db.ReadCommandVerbHandler.doVerb(ReadCommandVerbHandler.java:48) ~[apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.net.MessageDeliveryTask.run(MessageDeliveryTask.java:66) ~[apache-cassandra-3.11.6.jar:3.11.6]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0-zing_19.12.102.0]
	at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$FutureTask.run(AbstractLocalAwareExecutorService.java:165) ~[apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$LocalSessionFutureTask.run(AbstractLocalAwareExecutorService.java:137) [apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:113) [apache-cassandra-3.11.6.jar:3.11.6]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0-zing_19.12.102.0
```
I'm using Zing JDK:
```
[root@udb001 ~]# rpm -qa | grep zing
zing-jdk1.8.0-19.12.102.0-3.x86_64
zing-zst-8c.3.10.0-5.22.6.0.1.2.el7.x86_64
```
Cassandra version: 3.11.6
Apache ticket: https://issues.apache.org/jira/browse/CASSANDRA-15595

Thanks, Yakir.

**Comment by ben-manes** [comment]
This is Cassandra. It looks like it’s trying to read offheap but has an incorrect address offset. 

Good luck!

**Comment by yakirgb** [comment]
10x
