### ISSUE TITLE
ClassNotFoundException on cache creation

### ISSUE THREAD

**Issue by CDFN** [ben-manes/caffeine#445]
Hi, I'm trying to create LoadingCache using caffeine. Each time I start jar I'm receiving error below.
```
java.lang.IllegalStateException: com.github.benmanes.caffeine.cache.SSLAW
	at com.github.benmanes.caffeine.cache.LocalCacheFactory.newBoundedLocalCache(LocalCacheFactory.java:101) ~[?:?]
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalManualCache.<init>(BoundedLocalCache.java:3392) ~[?:?]
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalLoadingCache.<init>(BoundedLocalCache.java:3716) ~[?:?]
	at com.github.benmanes.caffeine.cache.Caffeine.build(Caffeine.java:1014) ~[?:?]
	at pl.flexhc.flexdrop.manager.PlayerManager.<init>(PlayerManager.kt:20) ~[?:?]
	at pl.flexhc.flexdrop.FlexDrop.onEnable(FlexDrop.kt:19) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:338) ~[server-1.8.8-R0.2-SNAPSHOT.jar:1.8.8_R0.1-SNAPSHOT]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336) [server-1.8.8-R0.2-SNAPSHOT.jar:1.8.8_R0.1-SNAPSHOT]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [server-1.8.8-R0.2-SNAPSHOT.jar:1.8.8_R0.1-SNAPSHOT]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:339) [server-1.8.8-R0.2-SNAPSHOT.jar:1.8.8_R0.1-SNAPSHOT]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:292) [server-1.8.8-R0.2-SNAPSHOT.jar:1.8.8_R0.1-SNAPSHOT]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [server-1.8.8-R0.2-SNAPSHOT.jar:1.8.8_R0.1-SNAPSHOT]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [server-1.8.8-R0.2-SNAPSHOT.jar:1.8.8_R0.1-SNAPSHOT]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [server-1.8.8-R0.2-SNAPSHOT.jar:1.8.8_R0.1-SNAPSHOT]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [server-1.8.8-R0.2-SNAPSHOT.jar:1.8.8_R0.1-SNAPSHOT]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [server-1.8.8-R0.2-SNAPSHOT.jar:1.8.8_R0.1-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.lang.ClassNotFoundException: com.github.benmanes.caffeine.cache.SSLAW
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_252]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[server-1.8.8-R0.2-SNAPSHOT.jar:1.8.8_R0.1-SNAPSHOT]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[server-1.8.8-R0.2-SNAPSHOT.jar:1.8.8_R0.1-SNAPSHOT]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_252]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_252]
	at com.github.benmanes.caffeine.cache.LocalCacheFactory.newBoundedLocalCache(LocalCacheFactory.java:95) ~[?:?]
	... 16 more
```

Code:
```kotlin
    val userCache: LoadingCache<UUID, DropPlayer> = Caffeine.newBuilder()
        .expireAfterAccess(1, TimeUnit.MINUTES)
        .expireAfterWrite(2, TimeUnit.MINUTES)
        .removalListener { key: UUID?, value: DropPlayer?, _ ->
            key ?: return@removalListener
            value ?: return@removalListener

        }
        .build {
            DropPlayer(it, false, listOf())
        }
```
IntellIJ can find this class, but it doesn't get included into jar.
![image](https://user-images.githubusercontent.com/41289688/90334804-7b1e5b00-dfd0-11ea-9548-cd66e0e39a78.png)
Issue also exists on older versions.

**Comment by CDFN** [comment]
Okay, this issue was my "rubber duck". I threw out minimize() out of shadowJar task and it worked. Anyway, I'll keep this issue open. I think it's not intended behavior

**Comment by ben-manes** [comment]
We use reflection to load generated classes specific to your cache configuration. This is to reduce rather memory overhead to avoid wasteful per-entry unused fields. That adds a little disk bloat or unloaded classes, which for servers is a good trade off.

If you use AOT that removes dead code (e.g. graalvm, proguard) then you have to whitelist the classes. There’s not much we can do to help since those intentionally break encapsulation by requiring that you learn our internal details.
