### ISSUE TITLE
Corretto 11 compatibility with Caffeine 

### ISSUE THREAD

**Issue by dearnani** [ben-manes/caffeine#473]
We upgraded the version to corretto11 docker image to have the run time environment, 

The API is trying to use -- Caffeine.newBuilder().expireAfterWrite method and it is throwing an issuue with below stacktrace, later added module jdk.unsupported given further stack below -- 

at java.base/java.security.AccessController.doPrivileged(Native Method)
at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:92)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
at java.base/java.lang.Class.getDeclaredFields0(Native Method)
at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3061)
at java.base/java.lang.Class.getDeclaredField(Class.java:2409)
at com.github.benmanes.caffeine.base.UnsafeAccess.objectFieldOffset(UnsafeAccess.java:57)
at com.github.benmanes.caffeine.cache.SSMS.<clinit>(Unknown Source)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
at com.github.benmanes.caffeine.cache.LocalCacheFactory.newBoundedLocalCache(Unknown Source)
at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalManualCache.<init>(BoundedLocalCache.java:3043)
at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalManualCache.<init>(BoundedLocalCache.java:3039)
at com.github.benmanes.caffeine.cache.Caffeine.build(Caffeine.java:926)

 **Added modules --** jdk.unsupported for the above, now it has the following exception. 

java.lang.IllegalStateException: com.github.benmanes.caffeine.cache.SSMSW : Error Type : SERVER : StackTrace : java.lang.IllegalStateException: com.github.benmanes.caffeine.cache.SSMSW
	at com.github.benmanes.caffeine.cache.LocalCacheFactory.newBoundedLocalCache(LocalCacheFactory.java:95)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalManualCache.<init>(BoundedLocalCache.java:3356)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalManualCache.<init>(BoundedLocalCache.java:3352)
	at com.github.benmanes.caffeine.cache.Caffeine.build(Caffeine.java:995)

**Comment by ben-manes** [comment]
`jdk.unsupported` is a required module, I'm glad you found that. There is some discussion of this in #273 that might offer clues. Maybe you need another flag? That thread also mentions `--add-exports java.base/sun.nio.ch=ALL-UNNAMED`.

**Comment by dearnani** [comment]
Hi @ben-manes , tried to pass this as jvm arguement, ran into the following exception at lower---

Caused by: java.lang.StackOverflowError: null
	at java.base/java.lang.String.startsWith(String.java:1470)
	at org.springframework.boot.loader.jar.Handler.getFileFromContext(Handler.java:173)
	at org.springframework.boot.loader.jar.Handler.parseURL(Handler.java:153)
	at java.base/java.net.URL.<init>(URL.java:674)
	at java.base/java.net.URL.<init>(URL.java:541)
	at java.base/jdk.internal.loader.URLClassPath$Loader.getResource(URLClassPath.java:634)
	at java.base/jdk.internal.loader.URLClassPath.getResource(URLClassPath.java:314)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:455)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:92)

**Comment by ben-manes** [comment]
Sorry but I can’t help, this is of directly caused by this library.

I’d try on AdoptJdk instead of a customized distribution. If that fails, then ask for help from your local build’s author. That error isn’t normal and from your environment.

**Comment by dearnani** [comment]
> Sorry but I can’t help, this is not directly caused by this library.
> 
> I’d try on AdoptJdk instead of a customized distribution. If that fails, then ask for help from your local build’s author. That error isn’t normal and from your environment.

May I know the recommended spring boot version for Caffeine 2.8.6. I tested with 2.2.2

**Comment by ben-manes** [comment]
Spring uses a BOM for the version that they have verified against. Our latest is backwards compatible with all Spring versions (1.4+) that offer support.
