### ISSUE TITLE
Possible loadingCache deadlock with performCleanUp 

### ISSUE THREAD

**Issue by kentwang929** [ben-manes/caffeine#527]
"ForkJoinPool.commonPool-worker-9" #181 daemon prio=5 os_prio=0 cpu=42739.37ms elapsed=33451.85s tid=0x00007fb5a8005000 nid=0x2429 waiting on condition  [0x00007fb4afcfb000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@14/Native Method)
	- parking to wait for  <0x00007fb93c3a9aa0> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(java.base@14/LockSupport.java:211)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@14/AbstractQueuedSynchronizer.java:714)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@14/AbstractQueuedSynchronizer.java:937)
	at java.util.concurrent.locks.ReentrantLock$Sync.lock(java.base@14/ReentrantLock.java:153)
	at java.util.concurrent.locks.ReentrantLock.lock(java.base@14/ReentrantLock.java:322)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.performCleanUp(BoundedLocalCache.java:1451)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$PerformCleanupTask.run(BoundedLocalCache.java:3334)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$PerformCleanupTask.exec(BoundedLocalCache.java:3321)
	at java.util.concurrent.ForkJoinTask.doExec(java.base@14/ForkJoinTask.java:290)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(java.base@14/ForkJoinPool.java:1016)
	at java.util.concurrent.ForkJoinPool.scan(java.base@14/ForkJoinPool.java:1665)
	at java.util.concurrent.ForkJoinPool.runWorker(java.base@14/ForkJoinPool.java:1598)
	at java.util.concurrent.ForkJoinWorkerThread.run(java.base@14/ForkJoinWorkerThread.java:177)

Several FJP threads started doing cleanup and are all waiting for 0x00007fb93c3a9aa0.  Other threads that use the same LoadingCache are also waiting for the same condition.  From our stack, we don't see any thread holding such condition.  The service is essentially dead at this point.

**Comment by kentwang929** [comment]
This is running the snapshot version of a89e7a6164 that has the possible computeIfAbsent fix.

**Comment by ben-manes** [comment]
That looks very much like a lost wakeup bug, e.g. see https://github.com/ben-manes/caffeine/issues/203#issuecomment-348674679.

You'll see in our code we only use the safe pattern,
```java
lock.lock();
try {
  ...
} finally {
  lock.unlock();
}
```

A lost wakeup by the operating system, such as Linux's futex bug, would break this. That only occurred at high concurrency as a very subtle race condition due to a missing memory barrier. If you are not impacted by that one, I think it is something similar in the underlying JVM / OS / hardware.

**Comment by kentwang929** [comment]
We are running on Ubuntu 18.04 (bionic) and using OpenJDK version 14.  Everything is relatively new.

**Comment by ben-manes** [comment]
Is that bare hardware or virtualized?

**Comment by kentwang929** [comment]
bare hardware

**Comment by ben-manes** [comment]
Unfortunately this is out of my area of expertise. If you read Gil's [description](https://groups.google.com/g/mechanical-sympathy/c/QbmpZxp6C64) and our locking code, it matches this behavior. In https://github.com/ben-manes/caffeine/issues/203#issuecomment-756629470, others had upgraded but still saw the problem. I don't know what might be the root cause, but I am confident it isn't the library. Of course if you can see where a mistake might be, I'll certainly jump on it.

You might need to escalate through a JDK / Linux provider to debug this.

**Comment by kentwang929** [comment]
Thanks, I will dig more and update you when I find something related to the library.

**Comment by ben-manes** [comment]
I’m going to close for now as there is nothing actionable yet. We can reopen or continue talking if you find anything.

**Comment by HashZhang** [comment]
I have something different to share, and I think this is not a deadlock and it is a problem related to the eviction mechanism. We also observed the problem of almost all threads are waiting with the thread dump:
```
"XNIO-2 task-5" #329 prio=5 os_prio=0 cpu=56327.98ms elapsed=6392.53s tid=0x0000fffeac39b900 nid=0x18f waiting on condition  [0x0000fffd5b0b8000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@17.0.2/Native Method)
	- parking to wait for  <0x00000006fc8bc8b0> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(java.base@17.0.2/LockSupport.java:211)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@17.0.2/AbstractQueuedSynchronizer.java:715)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@17.0.2/AbstractQueuedSynchronizer.java:938)
	at java.util.concurrent.locks.ReentrantLock$Sync.lock(java.base@17.0.2/ReentrantLock.java:153)
	at java.util.concurrent.locks.ReentrantLock.lock(java.base@17.0.2/ReentrantLock.java:322)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.performCleanUp(BoundedLocalCache.java:1458)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.afterWrite(BoundedLocalCache.java:1382)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2471)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2387)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108)
	at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
.......................................................
```
We are using caffeine with version: 2.9.3

with jdk version 17 as you can see in the thread stack. Our cache configuration is:
```
Caffeine.newBuilder().expireAfterWrite(1, TimeUnit.SECONDS).build();
```

We enabled the JFR and observed something very interesting:
1. From the view of thread dump, almost all threads were waiting on the "eviction lock", this lock is acquired when: (1) the value of key is computed and then execute `afterWrite()` which is almost all my threads are waiting. (2) The eviction task executed default by common ForkJoinPool, which got the thread stack as below:
```

"ForkJoinPool.commonPool-worker-2" #254 daemon prio=5 os_prio=0 cpu=102959.38ms elapsed=6394.88s tid=0x0000fffee80133c0 nid=0x141 waiting for monitor entry  [0x0000fffe0077e000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at java.util.concurrent.ConcurrentHashMap.computeIfPresent(java.base@17.0.2/ConcurrentHashMap.java:1819)
	- parking to wait for  <0x00000006ee8b6d40> (a java.util.concurrent.ForkJoinPool)
	- waiting to lock <0x00000006f047c0c8> (a java.util.concurrent.ConcurrentHashMap$Node)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.evictEntry(BoundedLocalCache.java:912)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.expireAfterWriteEntries(BoundedLocalCache.java:836)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.expireEntries(BoundedLocalCache.java:785)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.maintenance(BoundedLocalCache.java:1491)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.performCleanUp(BoundedLocalCache.java:1460)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$PerformCleanupTask.run(BoundedLocalCache.java:3359)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$PerformCleanupTask.exec(BoundedLocalCache.java:3346)
	at java.util.concurrent.ForkJoinTask.doExec(java.base@17.0.2/ForkJoinTask.java:373)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(java.base@17.0.2/ForkJoinPool.java:1182)
	at java.util.concurrent.ForkJoinPool.scan(java.base@17.0.2/ForkJoinPool.java:1655)
	at java.util.concurrent.ForkJoinPool.runWorker(java.base@17.0.2/ForkJoinPool.java:1622)
	at java.util.concurrent.ForkJoinWorkerThread.run(java.base@17.0.2/ForkJoinWorkerThread.java:165)
```
as shown above, the `eviction lock` is hold by this thread but it is blocked on ConcurrentHashMap$Node. Let's take a closer look through JFR:

![1662261106523](https://user-images.githubusercontent.com/15627489/188295405-f8482d8b-a504-4e3c-baad-8138bd7954db.png)

From the figure we can see that, this thread is blocking for 1.371s. And this lock is previously hold by XNIO2-task-7, which is loading value to this cache from JFR:
![1662261328350](https://user-images.githubusercontent.com/15627489/188295508-46d075de-01b3-4872-96d3-1394a7080dee.png)

Therefore, the problem is caused by:
1. Assume we have 64 threads reading from this cache using: `cache.get(key, k -> {....})`, cache has expire conf.
2. All threads are loading different keys, some of them(we name them as group 1) finished computing the key and execute `afterWrite`, some of them(we name them as group 2)  are computing the key.
3. ForkJoinPool.common execute the eviction task, if it acquired the eviction lock, it will block all threads in group 1. And while it is checking (using ConcurrentHashMap.computeIfAbsent) the key which is also computing by group 2, it will be blocked. If it takes too much time for ForkJoinPool.common waiting for group 2(maybe there is continous request to group 2), all group 1 thread will also be blocked for a long time and it seems like a dead lock
