### ISSUE TITLE
OOME when inserting concurrently in synthetic stress test

### ISSUE THREAD

**Issue by cruftex** [ben-manes/caffeine#59]
I am putting together some new Java Caching benchmarks. During a benchmark run I got a strange OOM exception with Caffeine (Version 2.1):

````
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at com.github.benmanes.caffeine.SingleConsumerQueue$$Lambda$4/2122912182.apply(Unknown Source)
        at com.github.benmanes.caffeine.SingleConsumerQueue.offer(SingleConsumerQueue.java:231)
        at com.github.benmanes.caffeine.SingleConsumerQueue.add(SingleConsumerQueue.java:255)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.afterWrite(BoundedLocalCache.java:796)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.putFast(BoundedLocalCache.java:1360)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.put(BoundedLocalCache.java:1296)
        at com.github.benmanes.caffeine.cache.LocalManualCache.put(LocalManualCache.java:64)
        at org.cache2k.benchmark.thirdparty.CaffeineCacheFactory$MyBenchmarkCacheAdapter.put(CaffeineCacheFactory.java:92)
        at org.cache2k.benchmark.thirdparty.CaffeineCacheFactory$MyBenchmarkCacheAdapter.put(CaffeineCacheFactory.java:69)
        at org.cache2k.benchmark.jmh.suite.noEviction.symmetrical.PopulateParallelOnceBenchmark.populateChunkInCache(PopulateParallelOnceBenchmark.java:47)
        at org.cache2k.benchmark.jmh.suite.noEviction.symmetrical.generated.PopulateParallelOnceBenchmark_populateChunkInCache_jmhTest.populateChunkInCache_ss_jmhSt
        at org.cache2k.benchmark.jmh.suite.noEviction.symmetrical.generated.PopulateParallelOnceBenchmark_populateChunkInCache_jmhTest.populateChunkInCache_SingleSh
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:430)
        at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:412)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
````

The interesting thing is, that the heap limit was 2G and the memory consumption, in case everything was inserted successful is only about 900MB. So, there is no real reason for an OOM.

You find the used setup described here: [cruftex.net : Java Caching Benchmarks 2016 - Part 1](http://cruftex.net/2016/03/16/Java-Caching-Benchmarks-2016-Part-1.html) The benchmark that failed was the "Populate Parallel Once" benchmark.

The full log of JMH is available at: http://cruftex.net/2016/03/16/result-thirdparty.CaffeineCacheFactory-ReadOnlyBenchmark-4.out.gz

It could be difficult to reproduce. During my runs this effect happened once. I will do regular runs with the latest Caffeine and JVM versions in a couple of days and report back.

**Comment by ben-manes** [comment]
I think this is because the benchmark is performing only inserts with no delay between operations on all of the available cores. In that case that the populating threads are given full cpu time quantums, do no additional work but increment a counter, and starve the asynchronous eviction so that it is unable to catch up. The [stress test](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/test/java/com/github/benmanes/caffeine/cache/Stresser.java) shows similar results, but demonstrates that adding a `Thread.yield()` resolves the issue.

The resolution will be when `SingleConsumerQueue` is replaced with a bounded array-based queue (preferably growing to a maximum to avoid wasting memory). The primary reason for the switch is because the hash table entry operation is the bottleneck and the queue doesn't show up in profiles. That leads to the conclusion that we probably want to prefer being more GC hygienic by not creating linked nodes rather than maximizing the queue's write rate. As a side effect the number of outstanding writes would be bounded, increasing the penalty in a synthetic test while avoiding the OOME.

Since this is only observable in artificial tests its been a low priority.

**Comment by ben-manes** [comment]
All evidence points to this only occurring in synthetic stress tests due to intentionally starving the eviction process. This occurred in CLHM as well, which delegated the penalty to a calling thread, and we couldn't find any hiccups occurring in practice (e.g. Cassandra load tests). I bring this up every so often when write rates are discussed on issue trackers to see if users have evidence that my analysis is incorrect. The scenario is good as a stress test, but makes no practical sense and any cache would be a poor data structure choice for this workload.

Closing as this has been on my [roadmap](https://github.com/ben-manes/caffeine/wiki/Roadmap) for a while, and I prefer to track it there unless it becomes a user issue.

Thanks for pinging me about it.
