### ISSUE TITLE
Using Caffeine in an ElasticSearch ingest plugin fails with an AccessControlException.

### ISSUE THREAD

**Issue by nielsbasjes** [ben-manes/caffeine#652]
In my project ( https://github.com/nielsbasjes/yauaa , https://yauaa.basjes.nl/) I now use Caffeine as the default caching implementation.

This works very nice yet in one place I ran into a problem.

The UDF I have that allows my project to be used in ElasticSearch as an ingest plugin ( https://github.com/nielsbasjes/yauaa/blob/master/udfs/elasticsearch/ ) fails (when run in a real ElasticSearch instance) with this exception:

```
Caused by: java.security.AccessControlException: access denied ("java.lang.reflect.ReflectPermission" "suppressAccessChecks")
         at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:485)
         at java.base/java.security.AccessController.checkPermission(AccessController.java:1068)
         at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:416)
         at java.base/java.lang.invoke.MethodHandles.privateLookupIn(MethodHandles.java:233)
         at com.github.benmanes.caffeine.cache.BaseMpscLinkedArrayQueue.<clinit>(MpscGrowableArrayQueue.java:662)
```

I suspect that the JVM used by ElasticSearch has specific security features enabled which make it fail.

As a workaround I have overridden the caching implementation back to the old one I was using before: https://github.com/nielsbasjes/yauaa/blob/master/udfs/elasticsearch/src/main/java/org/elasticsearch/plugin/ingest/yauaa/YauaaProcessor.java#L92

**Comment by nielsbasjes** [comment]
Ok, understood.
I have a workaround for my project so this is not blocking for me.
