### ISSUE TITLE
Nested cache using different keys results in deadlock

### ISSUE THREAD

**Issue by Bugsource** [ben-manes/caffeine#729]
Hi ben @ben-manes), 
My application is built on play framework whose default cache layer is `caffeine`. The case is that,  a process consists of several sub-processes some of which uses caffeine cache to store the result,  and the outer process merges all the results of sub-processes to get the final result and store it into caffeine cache too. It should be noted that the outer and inner process uses different key.

```scala
@Singleton
class NewsService @Inject() (
    newsModel: NewsModel,
    @NamedCache("newsCache") newsCache: AsyncCacheApi)(implicit asyncExecutionContext: AsyncExecutionContext) {

  def getNewsList(uin: Long, channelId: Int, page: Int): Future[Result] = {

    val key = getNewsListKey(uin, channelId, page)
    // outer process which use caffeine cache
    newsCache.getOrElseUpdate(key, 10.seconds) {
      for {
        newsByChannel <- getNewsByChannel(channelId, page)
        newsByAuthor  <-  getNewsByAuthor(uin, page)
      } yield {
        HttpUtil.returnCommonSuccessfulResult(Json.toJson(newsByChannel + newsByAuthor))
      }
    }
  }

 // inner process which use caffeine cache
  private def getNewsByChannel(channelId: Int, page: Int): Future[Seq[NewsDTO]] = {
    val key = getNewsChannelKey(channelId, page)
    newsCache.getOrElseUpdate(key, 300.seconds) {
      newsModel
        .getChannelNews(channelId, page)
    }
  }
}
```
Unfortunately,  this code probabilistically produces a deadlock in production environment. The stack is shown as below:
```
"application-akka.actor.default-dispatcher-11" #56 prio=5 os_prio=0 cpu=154197058.17ms elapsed=154454.83s allocated=30636K defined_classes=674 tid=0x00007fa0b4001000 nid=0x79 runnable
  [0x00007fa0bbefb000]
   java.lang.Thread.State: RUNNABLE
        at java.util.concurrent.ConcurrentHashMap.transfer(java.base@11.0.15-ga/ConcurrentHashMap.java:2477)
        - locked <0x00000007497ec400> (a java.util.concurrent.ConcurrentHashMap$ReservationNode)
        at java.util.concurrent.ConcurrentHashMap.addCount(java.base@11.0.15-ga/ConcurrentHashMap.java:2348)
        at java.util.concurrent.ConcurrentHashMap.compute(java.base@11.0.15-ga/ConcurrentHashMap.java:1994)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2344)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2327)
        at com.github.benmanes.caffeine.cache.LocalAsyncCache.get(LocalAsyncCache.java:91)
        at com.github.benmanes.caffeine.cache.LocalAsyncCache.get(LocalAsyncCache.java:82)
        at play.cache.caffeine.NamedCaffeineCache.get(NamedCaffeineCache.java:47)
        at play.api.cache.caffeine.CaffeineCacheApi.getOrElseUpdate(CaffeineCacheApi.scala:244)
        at services.NewsService.getNewsByChannel(NewsService.scala:445)
        at services.NewsService.$anonfun$getNewsList$2(NewsService.scala:558)
        at services.NewsService$$Lambda$1999/0x0000000800eb3c40.apply(Unknown Source)
        at play.api.cache.caffeine.CaffeineCacheApi.orElseAsJavaFuture$lzycompute$1(CaffeineCacheApi.scala:240)
        - locked <0x00000007497edda8> (a scala.runtime.LazyRef)
        at play.api.cache.caffeine.CaffeineCacheApi.orElseAsJavaFuture$1(CaffeineCacheApi.scala:239)
        at play.api.cache.caffeine.CaffeineCacheApi.$anonfun$getOrElseUpdate$3(CaffeineCacheApi.scala:242)
        at play.api.cache.caffeine.CaffeineCacheApi$$Lambda$867/0x000000080091d840.apply(Unknown Source)
        at scala.compat.java8.functionConverterImpls.AsJavaBiFunction.apply(FunctionConverters.scala:41)
        at com.github.benmanes.caffeine.cache.LocalAsyncCache.lambda$get$2(LocalAsyncCache.java:92)
        at com.github.benmanes.caffeine.cache.LocalAsyncCache$$Lambda$868/0x000000080091d040.apply(Unknown Source)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2346)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache$$Lambda$869/0x000000080091c840.apply(Unknown Source)
        at java.util.concurrent.ConcurrentHashMap.compute(java.base@11.0.15-ga/ConcurrentHashMap.java:1908)
        - locked <0x00000007497ec400> (a java.util.concurrent.ConcurrentHashMap$ReservationNode)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2344)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2327)
        at com.github.benmanes.caffeine.cache.LocalAsyncCache.get(LocalAsyncCache.java:91)
        at com.github.benmanes.caffeine.cache.LocalAsyncCache.get(LocalAsyncCache.java:82)
        at play.cache.caffeine.NamedCaffeineCache.get(NamedCaffeineCache.java:47)
        at play.api.cache.caffeine.CaffeineCacheApi.getOrElseUpdate(CaffeineCacheApi.scala:244)
        at services.NewsService.getNewsList(NewsService.scala:550)
        at controllers.NewsController.$anonfun$queryNewsList$1(NewsController.scala:55)
        at controllers.NewsController$$Lambda$1994/0x0000000800eb0840.apply(Unknown Source)
...

"application-akka.actor.default-dispatcher-10" #53 prio=5 os_prio=0 cpu=2881.99ms elapsed=150935.57s allocated=25908K defined_classes=271 tid=0x00007fa13800a800 nid=0x78 waiting for m
onitor entry  [0x00007fa0bbffc000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at java.util.concurrent.ConcurrentHashMap.compute(java.base@11.0.15-ga/ConcurrentHashMap.java:1923)
        - waiting to lock <0x00000007497ec400> (a java.util.concurrent.ConcurrentHashMap$ReservationNode)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2344)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2327)
        at com.github.benmanes.caffeine.cache.LocalAsyncCache.get(LocalAsyncCache.java:91)
        at com.github.benmanes.caffeine.cache.LocalAsyncCache.get(LocalAsyncCache.java:82)
        at play.cache.caffeine.NamedCaffeineCache.get(NamedCaffeineCache.java:47)
        at play.api.cache.caffeine.CaffeineCacheApi.getOrElseUpdate(CaffeineCacheApi.scala:244)
        at services.NewsService.getNewsList(NewsService.scala:550)
        at controllers.NewsController.$anonfun$queryNewsList$1(NewsController.scala:55)
        at controllers.NewsController$$Lambda$1994/0x0000000800eb0840.apply(Unknown Source)
```
It can be seen that the thread "application-akka.actor.default-dispatcher-11" locked <0x00000007497ec400> twice and all the other threads are waiting this lock to be released. Here comes the question, why these two functions(`getNewsByChannel` and   `getNewsList`) try to lock the same key when they use different cache keys? As i checked in history issues,  you have explained that: "The live-lock occurs when a recursive computation is performed for the same key. " But in this case,  the cache key is built to be different. Maybe the different keys result in the same hash code which occurs with small probability or i misunderstood something？

**Comment by ben-manes** [comment]
I reported this particular bug to Doug Lea and Martin Buchholz, who fixed it in jdk12. That was sync'd from Doug's repository in [JDK-8211283](https://bugs.openjdk.org/browse/JDK-8211283). See the [fix](https://github.com/openjdk/jdk/commit/53d3a4f50cef5712d42c7adcab75fed07354af15#diff-96692a9a81b55896a6d82cca1cf4f5835bcc146e774026c9f8cfc395d2f6beda) in `ConcurrentHashMap`.

If I recall correctly this occurs when the map grows and the internal table is resized. I don't recall why it failed during the resize rather than the compute itself, but it is moving entries between hash bins so there are races at play.

`ConcurrentHashMap` does not tolerate any computation that performs any other write into that map. That means `compute(k1)` may not write `compute(k2)`, `clear()`, etc. In those cases the map would livelock, but our jdk9-12 fixes catch this early to throw an exception. The reason is that those writes are very error prone and in another implementation could instead cause deadlocks. Even `HashMap` disallows it in jdk9, as it corrupts the jdk8 internal table to cause it to lose track of entries.

If possible, you should upgrade to a newer jdk. I don't know if this was backported and if a patch release would fail.

Given the above constraint, your logic violates the method's requirements. If you cannot change the logic, then you could decouple the locking from the hashmap and have it be done per-entry. The simplest way is to use a `Future` and the [FAQ](https://github.com/ben-manes/caffeine/wiki/Faq#recursive-computations) shows an example of using `AsyncCache` for simplicity.

Sorry if that is too much detail. Let me know if you have any questions.

**Comment by Bugsource** [comment]
> 



> I reported this particular bug to Doug Lea and Martin Buchholz, who fixed it in jdk12. That was sync'd from Doug's repository in [JDK-8211283](https://bugs.openjdk.org/browse/JDK-8211283). See the [fix](https://github.com/openjdk/jdk/commit/53d3a4f50cef5712d42c7adcab75fed07354af15#diff-96692a9a81b55896a6d82cca1cf4f5835bcc146e774026c9f8cfc395d2f6beda) in `ConcurrentHashMap`.
> 
> If I recall correctly this occurs when the map grows and the internal table is resized. I don't recall why it failed during the resize rather than the compute itself, but it is moving entries between hash bins so there are races at play.
> 
> `ConcurrentHashMap` does not tolerate any computation that performs any other write into that map. That means `compute(k1)` may not write `compute(k2)`, `clear()`, etc. In those cases the map would livelock, but our jdk9-12 fixes catch this early to throw an exception. The reason is that those writes are very error prone and in another implementation could instead cause deadlocks. Even `HashMap` disallows it in jdk9, as it corrupts the jdk8 internal table to cause it to lose track of entries.
> 
> If possible, you should upgrade to a newer jdk. I don't know if this was backported and if a patch release would fail.
> 
> Given the above constraint, your logic violates the method's requirements. If you cannot change the logic, then you could decouple the locking from the hashmap and have it be done per-entry. The simplest way is to use a `Future` and the [FAQ](https://github.com/ben-manes/caffeine/wiki/Faq#recursive-computations) shows an example of using `AsyncCache` for simplicity.
> 
> Sorry if that is too much detail. Let me know if you have any questions.

Thanks for your quick response!
The information you provide helps me a lot. I used to think that if don't do recursive computation against to the same key will not lead to race condition. But the truth is that any update to the map nested would produce live-lock,  as the description of the`compute` of `ConcurrentHashMap` says: "must not attempt to update any other mappings of this map". 

The root cause is probably like you said:  this occurs when the map grows and the internal table is resized,  given this into concern),  the live-lock only occurs among some of application instances can also be explained. 

It's strange that our application is built on JDK-11,  but don't throw an exception in this case. I guess it maybe swallowed by `Play` framework? Anyway,  it doesn't affect the conclusion: don't update the same cache in a recursive way.  We will try to change the logic or optimize based on the example.

Just a suggestion,  the document of `caffeine` may consider to emphasize this practice,  since the live-lock problem is hard to find cause and the `caffeine` is so popular among developers:)

**Comment by ben-manes** [comment]
> It's strange that our application is built on JDK-11, but don't throw an exception in this case. I guess it maybe swallowed by Play framework? 

In jdk9, it detects and throws for cases it detects during the computation. This case is after that computation to increment the size counter and assist in any on going resize, which I guess needs jdk12+. I'm surprised the computes didn't throw otherwise, but it is only best effort detection. The bullet proof way of a threadlocal was probably too expensive for Doug to feel comfortable doing inside of `ConcurrentHashMap` for detection on every write call.

> Just a suggestion, the document of caffeine may consider to emphasize this practice, since the live-lock problem is hard to find cause and the caffeine is so popular among developers:)

It's a `ConcurrentHashMap` issue which doesn't emphasize it and while I do put warnings in the JavaDoc, abstractions like Play's of course would not copy that across. Instead I worked with Doug to detect and fail fast, as I think the livelock is the worst experience. I haven't heard of any remaining cases since this fix, so we might have covered them all now. It's an unfortunate footgun, though.
