### ISSUE TITLE
No cleanUp for AsyncCache interface

### ISSUE THREAD

**Issue by anuragagarwal561994** [ben-manes/caffeine#748]
Hello @ben-manes I see that there is no cleanUp method for AsyncCache interface.

This is required for us for testing purposes.

When in testing we are using FakeTicker as suggested, most of the times the cleanUp happens on its own but sometimes the test fails as the refresh didn't trigger on it's own.

I think a cleanUp call would solve this.

**Comment by ben-manes** [comment]
Hi @anuragagarwal561994,

Please use `AsyncCache.synchronous().cleanUp()`.

**Comment by anuragagarwal561994** [comment]
@ben-manes just to confirm

```
org.junit.runners.model.TestTimedOutException: test timed out after 10 seconds
	at java.base@11.0.1/jdk.internal.misc.Unsafe.unpark(Native Method)
	at java.base@11.0.1/java.util.concurrent.locks.LockSupport.unpark(LockSupport.java:160)
	at java.base@11.0.1/java.util.concurrent.ForkJoinPool.signalWork(ForkJoinPool.java:1493)
	at java.base@11.0.1/java.util.concurrent.ForkJoinPool.externalPush(ForkJoinPool.java:1903)
	at java.base@11.0.1/java.util.concurrent.ForkJoinPool.externalSubmit(ForkJoinPool.java:1921)
	at java.base@11.0.1/java.util.concurrent.ForkJoinPool.execute(ForkJoinPool.java:2453)
	at app//com.github.benmanes.caffeine.cache.BoundedLocalCache.scheduleDrainBuffers(BoundedLocalCache.java:1575)
	at app//com.github.benmanes.caffeine.cache.BoundedLocalCache.afterRead(BoundedLocalCache.java:1236)
	at app//com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2523)
	at app//com.github.benmanes.caffeine.cache.LocalAsyncCache.get(LocalAsyncCache.java:90)
	at app//com.github.benmanes.caffeine.cache.LocalAsyncCache.get(LocalAsyncCache.java:81)
	at app//com.github.benmanes.caffeine.cache.LocalAsyncLoadingCache.get(LocalAsyncLoadingCache.java:134)
```

and

```
org.junit.runners.model.TestTimedOutException: test timed out after 10 seconds
	at java.base@11.0.1/jdk.internal.misc.Unsafe.unpark(Native Method)
	at java.base@11.0.1/java.util.concurrent.locks.LockSupport.unpark(LockSupport.java:160)
	at java.base@11.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer.unparkSuccessor(AbstractQueuedSynchronizer.java:709)
	at java.base@11.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1305)
	at java.base@11.0.1/java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:439)
	at app//com.github.benmanes.caffeine.cache.BoundedLocalCache.scheduleDrainBuffers(BoundedLocalCache.java:1580)
	at app//com.github.benmanes.caffeine.cache.BoundedLocalCache.afterRead(BoundedLocalCache.java:1236)
	at app//com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2523)
	at app//com.github.benmanes.caffeine.cache.LocalAsyncCache.get(LocalAsyncCache.java:90)
	at app//com.github.benmanes.caffeine.cache.LocalAsyncCache.get(LocalAsyncCache.java:81)
	at app//com.github.benmanes.caffeine.cache.LocalAsyncLoadingCache.get(LocalAsyncLoadingCache.java:134)
```

are associated with this issue only right?

**Comment by ben-manes** [comment]
That stacktrace does not make much sense to me. An exception is being thrown when a ReentrantLock is unlocked?

**Comment by anuragagarwal561994** [comment]
Oh so stacktrace is thrown because the test timed out after 10 seconds.

**Comment by ben-manes** [comment]
Unlocking should be a very fast operation. The cache's own logic is very fast, so I can't say how things are related from your description and stacktrace.

**Comment by ben-manes** [comment]
I see, JUnit4 is making a synthetic stacktrace for the test failure for reporting and interrupts the thread. I was not aware of that behavior as I avoided that framework version. Regardless, the stacktrace does not give us much except that the cache was done scheduling maintenance work.

```java
private Exception createTimeoutException(Thread thread) {
    StackTraceElement[] stackTrace = thread.getStackTrace();
    final Thread stuckThread = lookForStuckThread ? getStuckThread(thread) : null;
    Exception currThreadException = new TestTimedOutException(timeout, timeUnit);
    if (stackTrace != null) {
        currThreadException.setStackTrace(stackTrace);
        thread.interrupt();
    }
...
```

**Comment by anuragagarwal561994** [comment]
Yes, I have been getting exception for this test at different places. The only difference is using AsyncCache.

Let me try to find the root cause for the same.

**Comment by anuragagarwal561994** [comment]
There is some bug / issue I suspect. I tired for hours to debug the issue but couldn't debug on my own. Will need some help.

My test setup, I am adding an entry in via async load. Now I have set refresh after 15 minutes.

When I advance the time greater than 15 minutes, I expect the async load to be called again. Before doing this I have mocked a different output. When I get from cache this time, what ends up happening (once in several runs) is that the old value itself written to the cache with the current time instead of the new value.

It seems like a bug with the caffeine library, the reason I say is that when I checked my mock I could see that my async loader method was actually called second time which returned the new response and from the stacktrace I could also see that, but since the old value got written with the current time, now the old value is cached again in the cache and the reason why the test fails thereafter.

This doesn't happen everytime but when running the test more than 1000-2000 continuously times I could see one instance. 

I will try my best to re-produce the issue.

```
"ForkJoinPool.commonPool-worker-5@3262" daemon prio=5 tid=0x11 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at com.github.benmanes.caffeine.cache.BoundedLocalCache.setWriteTime(BoundedLocalCache.java:1459)
	  at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$remap$15(BoundedLocalCache.java:2775)
	  - locked <0x19a5> (a com.github.benmanes.caffeine.cache.PSR)
	  at com.github.benmanes.caffeine.cache.BoundedLocalCache$$Lambda$130.2054787417.apply(Unknown Source:-1)
	  at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1932)
	  - locked <0x1a14> (a java.util.concurrent.ConcurrentHashMap$Node)
	  at com.github.benmanes.caffeine.cache.BoundedLocalCache.remap(BoundedLocalCache.java:2712)
	  at com.github.benmanes.caffeine.cache.BoundedLocalCache.compute(BoundedLocalCache.java:2662)
	  at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$refreshIfNeeded$5(BoundedLocalCache.java:1325)
	  at com.github.benmanes.caffeine.cache.BoundedLocalCache$$Lambda$127.190153364.apply(Unknown Source:-1)
	  at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
	  at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907)
	  at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	  at java.util.concurrent.CompletableFuture$AsyncSupply.run$$$capture(CompletableFuture.java:1705)
	  at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:-1)
	  at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	  at java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:290)
	  at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:-1)
	  at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	  at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	  at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	  at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

This is the thread-dump from when the issue happened, might not be that useful but I could confirm in this flow I had the new value, yet while doing BoundedLocalCache.setWriteTime, the node was having the old value.

**Comment by ben-manes** [comment]
There are some improvements on master, https://github.com/ben-manes/caffeine/commit/9c6c5edb8b09ddbec6b9475809107833b71269e6, which removes the `setWriteTime`. You might try using the SNAPSHOT build and see if by chance that resolves your problem. The refresh is optimistic and best effort, so any detectable write will cause it to be dropped. The changes reduce cases where the cache was too aggressive in dropping valid refreshes because of the write timestamp being modified for internal purposes.

**Comment by anuragagarwal561994** [comment]
Sure @ben-manes let me try the master branch, meanwhile I am able to replicate the issue in a fresh code using test. Let me push the changes in a github repository if you would like to go through the test case in detail.

Meanwhile I can run the latest snapshot on my test as well to see if the issue is resolved in the latest build.

**Comment by ben-manes** [comment]
great, you can use the [Sonatype Snapshot Repository](https://oss.sonatype.org/content/repositories/snapshots/com/github/ben-manes/caffeine/caffeine/) with `3.1.2-SNAPSHOT` version for the dependency.

**Comment by anuragagarwal561994** [comment]
https://github.com/anuragagarwal561994/caffeine-refresh-issue

Above is the replicated test case. I am running this test case in IntelliJ using Repeat Until Failure feature and after few runs the test is getting stuck.

![Uploading Screenshot 2022-08-01 at 3.48.37 AM.png…]()

**Comment by anuragagarwal561994** [comment]
Tested the issue exists on version `3.1.2-SNAPSHOT` as well

<img width="1728" alt="Screenshot 2022-08-01 at 3 55 53 AM" src="https://user-images.githubusercontent.com/6075379/182047728-aaae595b-247a-4dd7-918b-fff6af8ca019.png">

**Comment by ben-manes** [comment]
I suspect that you are probably flooding the ForkJoinPool so it doesn't process it fast enough for your test runs. You could either configure a different thread pool and wait for it to settle down. Otherwise your tests will be flaky due to races.

**Comment by anuragagarwal561994** [comment]
@ben-manes been there done that 😄 

Even my first assumption was this and hence I tried with a custom single thread executor.

I have pushed new commit with the changes, it fails again.

By the way do you think, this needs to be taken to a new thread?

**Comment by ben-manes** [comment]
You would need to await termination of the executor and do so at the proper point within your test method before the failing assertion. Otherwise you are still allowing races to occur.

I am not an IntelliJ user so I haven't been able to reproduce it yet

**Comment by ben-manes** [comment]
Okay, got IntelliJ repeats working. If you set to `executor(Runnable::run)` it is fine (stopped at 20k runs). I think it's not waiting for the reload to complete in your threaded version.

**Comment by anuragagarwal561994** [comment]
Magical 🪄 

Works fine, I suspected the same issue because I knew that in junit test runner the threads and executors are generally shared.

But was not shutting the custom thread executor properly. Thanks a lot @ben-manes.

You will never let an issue linger in this repo for more than a day 😄 

Do you think this information can help others on https://github.com/ben-manes/caffeine/wiki/Testing

**Comment by ben-manes** [comment]
Triggering a refresh, shutting down, waiting, and then asserting works fine (20k runs). I modified the last few lines as,

```java
...
fakeTicker.advance(afterRefreshTime);
templateLoader.loadTemplate(KEY);

executorService.shutdown();
executorService.awaitTermination(1, TimeUnit.MINUTES);
loopWhileStatus(templateLoader, Result.SUCCESS);
assertSame(Result.API_FAILURE, templateLoader.loadTemplate(KEY));
```

Unfortunately I think this is general challenges with multi-threaded testing, so I don't think there is much we can add to that wiki page. I recommend `Awaitility` as it helps me coordinate threads in my tests when checking for concurrency related issues. Otherwise I use a same-thread executor as most tests do not care or want async behavior.

**Comment by anuragagarwal561994** [comment]
Yes makes sense, thanks. The issue can now be closed.
