### ISSUE TITLE
Could not serialize lambda in Spark Streaming job context

### ISSUE THREAD

**Issue by suhas-hoysala** [ben-manes/caffeine#767]
We are trying to integrate Caffeine caching in the context of a Spark streaming job. We use broadcast variables in order for our reference data to be accessible to each of the worker nodes. To initialize the cache, we adapted the benchmarking examples [here](https://github.com/ben-manes/caffeine/wiki/Benchmarks) and pass load functions so that we initialize the cache like:
```
private final Cache<K, V> cache;
public CaffeineCache(CacheFunction<K, V> loadFunction, CacheFunction<Iterable<? extends K>, Map<K,V>> loadAllFunction) {
        cache = Caffeine.newBuilder()
                .recordStats()
                .build(new CacheLoader<K, V>() {
                    @Override
                    public V load(K k) throws Exception {
                        return loadFunction.apply(k);
                    }
                    @Override public Map<K, V> loadAll(Iterable<? extends K> keys) throws Exception {
                        return loadAllFunction.apply(keys);
                    }
                });
    }
```
where
```
@FunctionalInterface
public interface CacheFunction<T, R> extends Serializable
```
and we generate the Broadcast variables like so:
```
private <T> Broadcast<T> generateBroadcast(SparkContext sc, Supplier<T> generator) {
        return JavaSparkContext.fromSparkContext(sc).broadcast(generator.get());
    }
```
however, while running our example, we experience the following:
```
22/09/03 04:17:13 ERROR org.apache.spark.streaming.scheduler.JobScheduler: Error running job streaming job 1662178631600 ms.0
com.esotericsoftware.kryo.KryoException: java.lang.RuntimeException: Could not serialize lambda
Serialization trace:
mappingFunction (com.github.benmanes.caffeine.cache.UnboundedLocalCache$UnboundedLocalLoadingCache)
cache ([INSERT CLASSPATH HERE].caffeine.impl.CaffeineCache)
cache ([INSERT CLASS HERE])
[INSERT VARNAME HERE] ([INSERT CLASS HERE])
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:101)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:508)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575)
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:79)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:508)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575)
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:79)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:508)
	at com.esotericsoftware.kryo.Kryo.writeObjectOrNull(Kryo.java:629)
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:86)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:508)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:651)
	at org.apache.spark.serializer.KryoSerializationStream.writeObject(KryoSerializer.scala:259)
	at org.apache.spark.broadcast.TorrentBroadcast$.$anonfun$blockifyObject$4(TorrentBroadcast.scala:319)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	at org.apache.spark.broadcast.TorrentBroadcast$.blockifyObject(TorrentBroadcast.scala:321)
	at org.apache.spark.broadcast.TorrentBroadcast.writeBlocks(TorrentBroadcast.scala:138)
	at org.apache.spark.broadcast.TorrentBroadcast.<init>(TorrentBroadcast.scala:91)
	at org.apache.spark.broadcast.TorrentBroadcastFactory.newBroadcast(TorrentBroadcastFactory.scala:35)
	at org.apache.spark.broadcast.BroadcastManager.newBroadcast(BroadcastManager.scala:77)
	at org.apache.spark.SparkContext.broadcast(SparkContext.scala:1517)
	at org.apache.spark.api.java.JavaSparkContext.broadcast(JavaSparkContext.scala:546)
	at [INSERT CLASSPATH HERE].BroadcastPersistenceManager.generateBroadcast(BroadcastPersistenceManager.java:138)
	at [INSERT CLASSPATH HERE].refreshAndGet(BroadcastPersistenceManager.java:114)
	at [INSERT CLASSPATH HERE].caffeine.profiler.CacheProfiler.lambda$transform$dab6494e$1(CacheProfiler.java:256)
	at org.apache.spark.streaming.api.java.JavaDStreamLike.$anonfun$foreachRDD$1(JavaDStreamLike.scala:272)
	at org.apache.spark.streaming.api.java.JavaDStreamLike.$anonfun$foreachRDD$1$adapted(JavaDStreamLike.scala:272)
	at org.apache.spark.streaming.dstream.DStream.$anonfun$foreachRDD$2(DStream.scala:629)
	at org.apache.spark.streaming.dstream.DStream.$anonfun$foreachRDD$2$adapted(DStream.scala:629)
	at org.apache.spark.streaming.dstream.ForEachDStream.$anonfun$generateJob$2(ForEachDStream.scala:51)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.streaming.dstream.DStream.createRDDWithLocalProperties(DStream.scala:417)
	at org.apache.spark.streaming.dstream.ForEachDStream.$anonfun$generateJob$1(ForEachDStream.scala:51)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.util.Try$.apply(Try.scala:213)
	at org.apache.spark.streaming.scheduler.Job.run(Job.scala:39)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler.$anonfun$run$1(JobScheduler.scala:256)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler.run(JobScheduler.scala:256)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Could not serialize lambda
	at com.esotericsoftware.kryo.serializers.ClosureSerializer.write(ClosureSerializer.java:69)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575)
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:79)
	... 42 more
Caused by: java.lang.NoSuchMethodException: com.github.benmanes.caffeine.cache.UnboundedLocalCache$UnboundedLocalLoadingCache$$Lambda$1571/1848218720.writeReplace()
	at java.lang.Class.getDeclaredMethod(Class.java:2130)
	at com.esotericsoftware.kryo.serializers.ClosureSerializer.write(ClosureSerializer.java:60)
	... 44 more
```
besides having our `CacheFunction<K,V>` lambda implement `Serializable`, what else would be needed? Would we need to write a custom `Cache` implementation that would also implement `Serializable`? Any suggestions would be helpful. Thanks.

**Comment by ben-manes** [comment]
We support native serialization begrudgingly, but Kryo is its own special flavor. The [writeReplace](https://github.com/ben-manes/caffeine/blob/042b3b6f86cfc28a426a19dc8ef7e34e1021ad66/caffeine/src/main/java/com/github/benmanes/caffeine/cache/UnboundedLocalCache.java#L1127-L1132) methods we implement use the [serialization proxy](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/main/java/com/github/benmanes/caffeine/cache/SerializationProxy.java) pattern (Effective Java 3rd, Item 90). This proxy simply recreates an empty cache with the same configuration.

If it diverges from native serialization then, then I guess with Kryo you could write a custom serializer?

**Comment by ben-manes** [comment]
It might be due to your anonymous `CacheLoader` instance not implementing serializable, as the interface does not inherit it. You might extract that to a nested inner class that implements both interfaces just in case.

**Comment by ben-manes** [comment]
Playing with it and what I think is best is to default to native serialization for the cache. Since it is not retaining the data it should be fast enough. However I am not familiar enough with Kryo to know why this fails,

```java
var kryo = new Kryo();
kryo.addDefaultSerializer(Cache.class, new JavaSerializer());
kryo.addDefaultSerializer(AsyncCache.class, new JavaSerializer());
kryo.addDefaultSerializer(LoadingCache.class, new JavaSerializer());
kryo.addDefaultSerializer(AsyncLoadingCache.class, new JavaSerializer());

var copy = kryo.copy(cache);
```

**Comment by ben-manes** [comment]
From google, it seems you have to register the private concrete types. That does not seem very feasible in most cases, though you might access via reflection. The Kryo serializers for Guava do not include the cache. I suspect the best approach is to create the cache on demand rather than serialize it. Sorry that I cannot be of more help.

**Comment by suhas-hoysala** [comment]
Thanks for looking into this. I had hoped that there'd be some native support for Kryo serialization; I appreciate your investigation regardless. For now we've just switched to using the `JavaSerializer` as a result. I'll add an additional comment if we can come up with a better solution.
