### ISSUE TITLE
by: java.lang.ClassNotFoundException: com.github.benmanes.caffeine.cache.SSAR

### ISSUE THREAD

**Issue by Rollczi** [ben-manes/caffeine#775]
```
java.lang.IllegalStateException: com.github.benmanes.caffeine.cache.SSAR
	at com.github.benmanes.caffeine.cache.LocalCacheFactory.loadFactory(LocalCacheFactory.java:90)
	at com.github.benmanes.caffeine.cache.LocalCacheFactory.newBoundedLocalCache(LocalCacheFactory.java:40)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalAsyncLoadingCache.<init>(BoundedLocalCache.java:4275)
	at com.github.benmanes.caffeine.cache.Caffeine.buildAsync(Caffeine.java:1155)
	at com.github.benmanes.caffeine.cache.Caffeine.buildAsync(Caffeine.java:1121)
[...]
Caused by: java.lang.ClassNotFoundException: com.github.benmanes.caffeine.cache.SSAR
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at com.github.benmanes.caffeine.cache.LocalCacheFactory.loadFactory(LocalCacheFactory.java:84)
	... 18 more
```

**Comment by Rollczi** [comment]
Resolved https://github.com/ben-manes/caffeine/discussions/762

**Comment by machitaoX** [comment]
how did you solved this problem？
