### ISSUE TITLE
caused by: java.lang.ClassNotFoundException: com.github.benmanes.caffeine.cache.SSW

### ISSUE THREAD

**Issue by ashraf-revo** [ben-manes/caffeine#850]
i am getting this error as class not found when using spring native 

`Caused by: java.lang.IllegalStateException: com.github.benmanes.caffeine.cache.SSW
	at com.github.benmanes.caffeine.cache.LocalCacheFactory.loadFactory(LocalCacheFactory.java:90) ~[na:na]
	at com.github.benmanes.caffeine.cache.LocalCacheFactory.newBoundedLocalCache(LocalCacheFactory.java:40) ~[na:na]
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalManualCache.<init>(BoundedLocalCache.java:3891) ~[gateway:na]
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalManualCache.<init>(BoundedLocalCache.java:3887) ~[gateway:na]
	at com.github.benmanes.caffeine.cache.Caffeine.build(Caffeine.java:1053) ~[na:na]
	at org.springframework.cache.caffeine.CaffeineCacheManager.createNativeCaffeineCache(CaffeineCacheManager.java:254) ~[gateway:6.0.3]
`

`Caused by: java.lang.ClassNotFoundException: com.github.benmanes.caffeine.cache.SSW
	at java.base@17.0.5/java.lang.Class.forName(DynamicHub.java:1132) ~[gateway:na]
	at java.base@17.0.5/java.lang.Class.forName(DynamicHub.java:1105) ~[gateway:na]
	at com.github.benmanes.caffeine.cache.LocalCacheFactory.loadFactory(LocalCacheFactory.java:84) ~[na:na]
	... 56 common frames omitted
`

**Comment by ben-manes** [comment]
Are you using proguard, aot, or some other process that can remove classes? These classes are dynamically loaded so a naive dead code elimination strategy won't work and you'd need to whitelist their inclusion.

**Comment by ashraf-revo** [comment]
yes iam using spring with native grallvm

**Comment by ben-manes** [comment]
You can reach out to them as they manage the dependency, or look at what micronaut and quarkus do. The last I knew their support for libraries was an experimental and broken (https://github.com/spring-projects-experimental/spring-native/issues/465). From their [docs](https://docs.spring.io/spring-boot/docs/current/reference/html/native-image.html#native-image.advanced.known-limitations), it sounds like it was too much of a lift to handle initially and they defer it to users to figure it out. They have a [smoke test](https://github.com/spring-projects/spring-aot-smoke-tests) but I don't see where they register the classes, so that could be a starting point to engage them on. Unfortunately you'll need to engage with framework authors on this as it is out of scope for the library, as AOT is no longer proper Java and implies framework specific quirks that we can't resolve.

**Comment by solerman** [comment]
To anyone hitting this in spring boot 3, add @EnableCaching to your application even if you don't use Spring's cache features
