### ISSUE TITLE
NoClassDefFoundError for RemovalCause

### ISSUE THREAD

**Issue by kdempster** [ben-manes/caffeine#98]
Hi,

I am not sure if you can help, but we are using version 2.3.1 with Spring 4.17 (a version of Spring that has yet to integration with Catteine)

The following is our configuration :

cache = Caffeine.newBuilder()
                .maximumSize(Long.parseLong(cacheSize))
                .expireAfterWrite(Long.parseLong(cacheExpireTime), TimeUnit.MINUTES)
                .build();

cacheSize = 5
cacheExpireTime = 5

We are seeing the following exception when the cache attempts to do an eviction :

Jul 01, 2016 3:14:43 PM org.apache.catalina.loader.WebappClassLoader findClass
WARNING: WebappClassLoader.findClassInternal(com.github.benmanes.caffeine.cache.RemovalCause) security exception: access denied ("java.io.FilePermission" "C:\Java\tools\apache
-tomcat-7.0.42-pacman\webapps\cmt\WEB-INF\classes\com\github\benmanes\caffeine\cache\RemovalCause.class" "read")
java.security.AccessControlException: access denied ("java.io.FilePermission" "C:\Java\tools\apache-tomcat-7.0.42-pacman\webapps\cmt\WEB-INF\classes\com\github\benmanes\caffei
ne\cache\RemovalCause.class" "read")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
        at java.security.AccessController.checkPermission(AccessController.java:884)
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
        at java.lang.SecurityManager.checkRead(SecurityManager.java:888)
        at java.io.File.exists(File.java:814)
        at org.apache.naming.resources.FileDirContext.file(FileDirContext.java:768)
        at org.apache.naming.resources.FileDirContext.doLookup(FileDirContext.java:198)
        at org.apache.naming.resources.BaseDirContext.lookup(BaseDirContext.java:483)
        at org.apache.naming.resources.ProxyDirContext.lookup(ProxyDirContext.java:308)
        at org.apache.catalina.loader.WebappClassLoader.findResourceInternal(WebappClassLoader.java:2970)
        at org.apache.catalina.loader.WebappClassLoader.findClassInternal(WebappClassLoader.java:2830)
        at org.apache.catalina.loader.WebappClassLoader.findClass(WebappClassLoader.java:1173)
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1681)
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1559)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.expireAfterWriteEntries(BoundedLocalCache.java:697)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.expireEntries(BoundedLocalCache.java:654)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.maintenance(BoundedLocalCache.java:1019)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.performCleanUp(BoundedLocalCache.java:998)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache$PerformCleanupTask.run(BoundedLocalCache.java:2835)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache$PerformCleanupTask.exec(BoundedLocalCache.java:2824)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

Jul 01, 2016 3:14:43 PM com.github.benmanes.caffeine.cache.BoundedLocalCache$PerformCleanupTask exec
SEVERE: Exception thrown when performing the maintenance task
java.lang.NoClassDefFoundError: com/github/benmanes/caffeine/cache/RemovalCause
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.expireAfterWriteEntries(BoundedLocalCache.java:697)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.expireEntries(BoundedLocalCache.java:654)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.maintenance(BoundedLocalCache.java:1019)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.performCleanUp(BoundedLocalCache.java:998)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache$PerformCleanupTask.run(BoundedLocalCache.java:2835)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache$PerformCleanupTask.exec(BoundedLocalCache.java:2824)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.ClassNotFoundException: com.github.benmanes.caffeine.cache.RemovalCause
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1714)
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1559)
        ... 10 more

**Comment by ben-manes** [comment]
Unfortunately I might not be able to help much since I haven't used Tomcat or Spring in a long time. 

I guess the first step is verifying that the class is in your WAR, due to the underlying `ClassNotFoundException`. Since you also received an `AccessControlException: access denied ("java.io.FilePermission"` when trying to load it, you might have to check your `SecurityManager` restrictions. From what I can gather Googling, you might need to add the jar to the deployment assembly.

**Comment by kdempster** [comment]
Thanks for the quick reply.  I am not sure of what the problem was, but by forcing the classloader to load the RemoveCause enum in the class that i defined the cache seemed to do the trick.  I simply logged the name of the enum.

**Comment by ben-manes** [comment]
Glad to hear its working. It might be a quirk due to Tomcat trying to isolate multiple webapps in their own classloaders and ForkJoinPool being shared across the JVM. Some weird interaction that I don't get since I typically embed jetty instead.
